-- =========================================================
-- 1) BẢNG NGƯỜI DÙNG
-- =========================================================
CREATE TABLE USERS(
    MAND VARCHAR2(50),
    EMAIL VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(255) NOT NULL,
    AVATAR_URL VARCHAR2(1000) NULL,
    ROLE_NAME VARCHAR2(50) DEFAULT 'STUDENT' NOT NULL,
    PASSWORD_HASH VARCHAR2(512) NOT NULL,
    PASSWORD_SALT VARCHAR2(256) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    FAILED_LOGIN_COUNT NUMBER(10) DEFAULT 0,
    LOCKOUT_END_UTC TIMESTAMP(6) NULL
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (MAND);
ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL);
ALTER TABLE USERS ADD CONSTRAINT CK_USERS_IS_ACTIVE CHECK (IS_ACTIVE IN (0,1));

CREATE INDEX IX_USERS_ROLE ON USERS (ROLE_NAME);

-- =========================================================
-- 2) BẢNG NHẬT KÝ HỆ THỐNG
-- =========================================================
CREATE TABLE AUDIT_TRAIL (
    ID            VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    WHO           VARCHAR2(100) NOT NULL,
    ACTION        VARCHAR2(200) NOT NULL,
    EVENT_AT_UTC  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CLIENT_IP     VARCHAR2(45),
    USER_AGENT    VARCHAR2(400)
);

-- =========================================================
-- 3) BẢNG TOKEN KHÔI PHỤC MẬT KHẨU
-- =========================================================
CREATE TABLE PASSWORD_RESET_TOKENS (
    ID               VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    EMAIL            VARCHAR2(255) NOT NULL,  -- tham chiếu USERS.EMAIL
    TOKEN            VARCHAR2(256) NOT NULL,
    EXPIRES_AT_UTC   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT_UTC   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    IS_USED          NUMBER(1,0) DEFAULT 0 NOT NULL
);

ALTER TABLE PASSWORD_RESET_TOKENS
  ADD CONSTRAINT UQ_PRT_TOKEN UNIQUE (TOKEN);

ALTER TABLE PASSWORD_RESET_TOKENS
  ADD CONSTRAINT FK_PRT_EMAIL
  FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL);

CREATE INDEX IX_PRT_EMAIL       ON PASSWORD_RESET_TOKENS(EMAIL);

-- =========================================================
-- 4) TERMS (Học kỳ / năm học)
-- =========================================================
CREATE TABLE TERMS (
    ID          VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    YEAR_ID     VARCHAR2(20),
    START_DATE  DATE NOT NULL,
    END_DATE    DATE NOT NULL
);

CREATE INDEX IX_TERMS_START ON TERMS (START_DATE);

-- =========================================================
-- 5) CRITERIA (Tiêu chí DRL)
-- =========================================================
CREATE TABLE CRITERIA (
    ID         VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    GROUP_NO   NUMBER(3)    NOT NULL,
    NAME       VARCHAR2(255) NOT NULL,
    MAX_POINT  NUMBER(5)    NOT NULL
);

CREATE INDEX IX_CRITERIA_GROUP ON CRITERIA (GROUP_NO);

-- =========================================================
-- 6) ACTIVITIES (Hoạt động rèn luyện)
-- =========================================================
CREATE TABLE ACTIVITIES (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TITLE           VARCHAR2(255) NOT NULL,
    DESCRIPTION     CLOB,
    TERM_ID         VARCHAR2(32)  NOT NULL,
    CRITERION_ID    VARCHAR2(32),
    START_AT        TIMESTAMP(6)  NOT NULL,
    END_AT          TIMESTAMP(6)  NOT NULL,
    STATUS          VARCHAR2(20)  DEFAULT 'OPEN' NOT NULL, -- OPEN|CLOSED|CANCELLED...
    MAX_SEATS       NUMBER,
    LOCATION        VARCHAR2(200),
    POINTS          NUMBER(5,2),
    APPROVAL_STATUS VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL, -- PENDING|APPROVED|REJECTED
    APPROVED_BY     VARCHAR2(50),
    APPROVED_AT     TIMESTAMP(6),
    ORGANIZER_ID    VARCHAR2(50),
    CREATED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE ACTIVITIES 
    ADD CONSTRAINT CK_ACT_STATUS CHECK (STATUS IN ('OPEN','CLOSED','CANCELLED'));
ALTER TABLE ACTIVITIES 
    ADD CONSTRAINT CK_ACT_APPROVAL 
    CHECK (APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED'))
ALTER TABLE ACTIVITIES
  ADD CONSTRAINT FK_ACT_TERM
  FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE ACTIVITIES
    ADD CONSTRAINT FK_ACT_CRITERIA
    FOREIGN KEY (CRITERION_ID) REFERENCES CRITERIA(ID);
ALTER TABLE ACTIVITIES 
    ADD CONSTRAINT FK_ACT_APPROVED_BY 
    FOREIGN KEY (APPROVED_BY) REFERENCES USERS(MAND);
ALTER TABLE ACTIVITIES 
    ADD CONSTRAINT FK_ACT_ORG 
    FOREIGN KEY (ORGANIZER_ID) REFERENCES USERS(MAND);

CREATE INDEX IX_ACT_TERM      ON ACTIVITIES(TERM_ID);
CREATE INDEX IX_ACT_CRITERION ON ACTIVITIES(CRITERION_ID);
CREATE INDEX IX_ACT_APPROVAL  ON ACTIVITIES(APPROVAL_STATUS);
CREATE INDEX IX_ACT_STATUS    ON ACTIVITIES(STATUS);
CREATE INDEX IX_ACT_ORG       ON ACTIVITIES(ORGANIZER_ID);

-- =========================================================
-- 7) REGISTRATIONS (Đăng ký hoạt động)
-- =========================================================
CREATE TABLE REGISTRATIONS (
    ID             VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    ACTIVITY_ID    VARCHAR2(32) NOT NULL,
    STUDENT_ID     VARCHAR2(50) NOT NULL,  -- USERS.MAND
    STATUS         VARCHAR2(20) DEFAULT 'REGISTERED' NOT NULL, -- REGISTERED|CHECKED_IN|CANCELLED...
    REGISTERED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CHECKED_IN_AT  TIMESTAMP(6)
);

ALTER TABLE REGISTRATIONS 
    ADD CONSTRAINT CK_REG_STATUS 
    CHECK (STATUS IN ('REGISTERED','CHECKED_IN','CANCELLED'));
ALTER TABLE REGISTRATIONS 
    ADD CONSTRAINT UQ_REG_ACTIVITY_STUDENT 
    UNIQUE (ACTIVITY_ID, STUDENT_ID);
ALTER TABLE REGISTRATIONS
  ADD CONSTRAINT FK_REG_ACT
  FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID) ON DELETE CASCADE;
ALTER TABLE REGISTRATIONS
  ADD CONSTRAINT FK_REG_STU
  FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;

CREATE INDEX IX_REG_ACT         ON REGISTRATIONS(ACTIVITY_ID);
CREATE INDEX IX_REG_STUDENT     ON REGISTRATIONS(STUDENT_ID);

-- =========================================================
-- 8) NOTIFICATIONS
-- =========================================================
CREATE TABLE NOTIFICATIONS (
    ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TITLE        VARCHAR2(255) NOT NULL,
    CONTENT      CLOB,
    CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TARGET_ROLE  VARCHAR2(30),
    TO_USER_ID   VARCHAR2(50) -- USERS.MAND (nullable nếu gửi theo ROLE)
);

ALTER TABLE NOTIFICATIONS
  ADD CONSTRAINT FK_NOTI_USER
  FOREIGN KEY (TO_USER_ID) REFERENCES USERS(MAND);

CREATE INDEX IX_NOTI_TOUSER     ON NOTIFICATIONS(TO_USER_ID);


-- =========================================================
-- 9) NOTIFICATIONS_READS (Theo dõi trạng thái đã đọc)
-- =========================================================
CREATE TABLE NOTIFICATION_READS (
  ID               VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
  NOTIFICATION_ID  VARCHAR2(32) NOT NULL,    -- FK -> NOTIFICATIONS(ID)
  STUDENT_ID       VARCHAR2(50) NOT NULL,    -- FK -> USERS(MAND)
  IS_READ          NUMBER(1,0) DEFAULT 0 NOT NULL,  -- 0/1
  READ_AT          TIMESTAMP(6)
);

ALTER TABLE NOTIFICATION_READS
  ADD CONSTRAINT FK_NREADS_NOTI FOREIGN KEY (NOTIFICATION_ID)
  REFERENCES NOTIFICATIONS(ID) ON DELETE CASCADE;

ALTER TABLE NOTIFICATION_READS
  ADD CONSTRAINT FK_NREADS_STU FOREIGN KEY (STUDENT_ID)
  REFERENCES USERS(MAND) ON DELETE CASCADE;

ALTER TABLE NOTIFICATION_READS
  ADD CONSTRAINT UQ_NREADS UNIQUE (NOTIFICATION_ID, STUDENT_ID);

CREATE INDEX IX_NREADS_STU ON NOTIFICATION_READS (STUDENT_ID, IS_READ);

-- =========================================================
-- 10) SCORES (Điểm rèn luyện tổng kết theo học kỳ)
-- =========================================================
CREATE TABLE SCORES (
  ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STUDENT_ID    VARCHAR2(50)   NOT NULL,  -- FK USERS(MAND)
  TERM_ID       VARCHAR2(32)   NOT NULL,  -- FK TERMS(ID)
  TOTAL         NUMBER(5,2)    DEFAULT 70 NOT NULL,  -- tổng điểm (0–100)
  STATUS        VARCHAR2(20)   DEFAULT 'PROVISIONAL' NOT NULL, -- PROVISIONAL | APPROVED
  APPROVED_BY   VARCHAR2(50),   -- MAND của người duyệt (cố vấn hoặc admin)
  APPROVED_AT   TIMESTAMP(6),   -- thời điểm duyệt
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE SCORES 
    ADD CONSTRAINT CK_SCORES_STATUS 
    CHECK (STATUS IN ('PROVISIONAL', 'APPROVED'));

ALTER TABLE SCORES 
    ADD CONSTRAINT FK_SCORES_STUDENT
    FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;

ALTER TABLE SCORES 
    ADD CONSTRAINT FK_SCORES_TERM
    FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;

ALTER TABLE SCORES ADD CONSTRAINT UQ_SCORES_STUDENT_TERM
  UNIQUE (STUDENT_ID, TERM_ID);

CREATE INDEX IX_SCORES_STATUS ON SCORES (STATUS);
CREATE INDEX IX_SCORES_TERM ON SCORES (TERM_ID);

-- =========================================================
-- 11) DEPARTMENTS (Khoa/Phòng)
-- =========================================================
CREATE TABLE DEPARTMENTS (
    ID    VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    NAME  VARCHAR2(150) NOT NULL
);

ALTER TABLE DEPARTMENTS
  ADD CONSTRAINT UQ_DEPARTMENTS_NAME UNIQUE (NAME);

CREATE INDEX IX_DEPT_NAME ON DEPARTMENTS (NAME);

-- =========================================================
-- 12) CLASSES (Lớp)
-- =========================================================
CREATE TABLE CLASSES (
    ID             VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    NAME           VARCHAR2(100) NOT NULL,
    DEPARTMENT_ID  VARCHAR2(32)  NULL  -- FK -> DEPARTMENTS(ID)
);

ALTER TABLE CLASSES
  ADD CONSTRAINT UQ_CLASSES_NAME UNIQUE (NAME);

ALTER TABLE CLASSES
  ADD CONSTRAINT FK_CLASSES_DEPT
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);

CREATE INDEX IX_CLASSES_DEPT ON CLASSES (DEPARTMENT_ID);

-- =========================================================
-- 13) STUDENTS (Hồ sơ sinh viên)
-- =========================================================
CREATE TABLE STUDENTS (
    USER_ID        VARCHAR2(50)  PRIMARY KEY, -- FK -> USERS(MAND)
    STUDENT_CODE   VARCHAR2(50),              -- Mã SV (unique nếu cần)
    CLASS_ID       VARCHAR2(32),              -- FK -> CLASSES(ID)
    DEPARTMENT_ID  VARCHAR2(32),              -- FK -> DEPARTMENTS(ID)
    DOB            DATE,                      -- Ngày sinh
    GENDER         VARCHAR2(10),              -- MALE|FEMALE|OTHER
    PHONE          VARCHAR2(30),
    ADDRESS        VARCHAR2(255)
);

ALTER TABLE STUDENTS
  ADD CONSTRAINT FK_STUDENTS_USER
  FOREIGN KEY (USER_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;

ALTER TABLE STUDENTS
  ADD CONSTRAINT FK_STUDENTS_CLASS
  FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID);

ALTER TABLE STUDENTS
  ADD CONSTRAINT FK_STUDENTS_DEPT
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);

ALTER TABLE STUDENTS
  ADD CONSTRAINT UQ_STUDENTS_CODE UNIQUE (STUDENT_CODE);

ALTER TABLE STUDENTS
   ADD CONSTRAINT CK_STUDENTS_GENDER CHECK (GENDER IN ('MALE','FEMALE','OTHER'));

CREATE INDEX IX_STUDENTS_CLASS ON STUDENTS (CLASS_ID);
CREATE INDEX IX_STUDENTS_DEPT  ON STUDENTS (DEPARTMENT_ID);

-- =========================================================
-- 14) PROOFS (Minh chứng hoạt động của sinh viên)
-- =========================================================
CREATE TABLE PROOFS (
    ID               VARCHAR2(32)  DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    REGISTRATION_ID  VARCHAR2(32)  NOT NULL,   -- FK -> REGISTRATIONS(ID)
    STUDENT_ID       VARCHAR2(50)  NOT NULL,   -- FK -> USERS(MAND)
    ACTIVITY_ID      VARCHAR2(32)  NOT NULL,   -- FK -> ACTIVITIES(ID)
    FILE_NAME        VARCHAR2(255) NOT NULL,   -- tên gốc (đã sanitize)
    STORED_PATH      VARCHAR2(500) NOT NULL,   -- /uploads/proofs/{sid}/{aid}/{guid.ext}
    CONTENT_TYPE     VARCHAR2(100) NOT NULL,
    FILE_SIZE        NUMBER        NOT NULL,   -- bytes
    SHA256_HEX       VARCHAR2(64),             -- chống trùng nội dung
    NOTE             VARCHAR2(300),            -- ghi chú của SV (tuỳ chọn)
    STATUS           VARCHAR2(20)  DEFAULT 'SUBMITTED' NOT NULL, -- SUBMITTED|APPROVED|REJECTED
    CREATED_AT_UTC   TIMESTAMP(6) WITH TIME ZONE
                        DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    REVIEWED_AT_UTC  TIMESTAMP(6) WITH TIME ZONE
);

ALTER TABLE PROOFS
  ADD CONSTRAINT CK_PROOFS_STATUS
  CHECK (STATUS IN ('SUBMITTED','APPROVED','REJECTED'));

ALTER TABLE PROOFS
  ADD CONSTRAINT FK_PROOFS_REG
  FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATIONS(ID) ON DELETE CASCADE;

ALTER TABLE PROOFS
  ADD CONSTRAINT FK_PROOFS_USER
  FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;

ALTER TABLE PROOFS
  ADD CONSTRAINT FK_PROOFS_ACT
  FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID) ON DELETE CASCADE;

CREATE INDEX IX_PROOFS_STU_ACT ON PROOFS (STUDENT_ID, ACTIVITY_ID);
CREATE INDEX IX_PROOFS_REG     ON PROOFS (REGISTRATION_ID);
CREATE INDEX IX_PROOFS_STATUS  ON PROOFS (STATUS);
CREATE INDEX IX_PROOFS_SHA256  ON PROOFS (SHA256_HEX);

-- =========================================================
-- 15) FEEDBACKS (Phản hồi điểm rèn luyện của sinh viên)
-- =========================================================
CREATE TABLE FEEDBACKS (
    ID            VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    STUDENT_ID    VARCHAR2(50)  NOT NULL,   -- FK -> USERS(MAND)
    TERM_ID       VARCHAR2(32)  NOT NULL,   -- FK -> TERMS(ID)
    CRITERION_ID  VARCHAR2(32),              -- FK -> CRITERIA(ID) (tùy chọn)
    TITLE         VARCHAR2(255) NOT NULL,    -- Tiêu đề phản hồi
    CONTENT       CLOB NOT NULL,             -- Nội dung phản hồi
    STATUS        VARCHAR2(20) DEFAULT 'SUBMITTED' NOT NULL,  -- DRAFT|SUBMITTED|RESPONDED|CLOSED
    RESPONSE      CLOB,                      -- Trả lời từ khoa/cố vấn
    CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP(6),
    RESPONDED_AT  TIMESTAMP(6)
);

ALTER TABLE FEEDBACKS
  ADD CONSTRAINT CK_FEEDBACKS_STATUS
  CHECK (STATUS IN ('DRAFT','SUBMITTED','RESPONDED','CLOSED'));

ALTER TABLE FEEDBACKS
  ADD CONSTRAINT FK_FEEDBACKS_STUDENT
  FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;

ALTER TABLE FEEDBACKS
  ADD CONSTRAINT FK_FEEDBACKS_TERM
  FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;

ALTER TABLE FEEDBACKS
  ADD CONSTRAINT FK_FEEDBACKS_CRITERION
  FOREIGN KEY (CRITERION_ID) REFERENCES CRITERIA(ID);

CREATE INDEX IX_FEEDBACKS_STU_TERM ON FEEDBACKS (STUDENT_ID, TERM_ID);
CREATE INDEX IX_FEEDBACKS_STATUS   ON FEEDBACKS (STATUS);
CREATE INDEX IX_FEEDBACKS_TERM     ON FEEDBACKS (TERM_ID);

-- =========================================================
-- 3) CLASS_LECTURERS (Giảng viên quản lý lớp)
-- =========================================================
CREATE TABLE CLASS_LECTURERS (
  ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
  CLASS_ID     VARCHAR2(32) NOT NULL,
  LECTURER_ID  VARCHAR2(50) NOT NULL
);

ALTER TABLE CLASS_LECTURERS
  ADD CONSTRAINT FK_CM_CLASS
  FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID) ON DELETE CASCADE;

ALTER TABLE CLASS_LECTURERS
  ADD CONSTRAINT FK_CM_LECTURER
  FOREIGN KEY (LECTURER_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;

ALTER TABLE CLASS_LECTURERS
  ADD CONSTRAINT UQ_CLASS_MANAGER UNIQUE (CLASS_ID, LECTURER_ID);

CREATE INDEX IX_CM_LECTURER ON CLASS_LECTURERS (LECTURER_ID);
