-- QUẢN LÝ ĐIỂM RÈN LUYỆN - DATABASE SCHEMA

-- =========================================================
-- 1) BẢNG NGƯỜI DÙNG
-- =========================================================
CREATE TABLE USERS(
    MAND VARCHAR2(50),
    EMAIL VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(255) NOT NULL,
    AVATAR_URL VARCHAR2(1000) NULL,
    ROLE_NAME VARCHAR2(50) DEFAULT 'STUDENT' NOT NULL,
    PASSWORD_HASH VARCHAR2(512) NOT NULL,
    PASSWORD_SALT VARCHAR2(256) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    FAILED_LOGIN_COUNT NUMBER(10) DEFAULT 0,
    LOCKOUT_END_UTC TIMESTAMP(6) NULL
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (MAND);
ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL);
ALTER TABLE USERS ADD CONSTRAINT CK_USERS_IS_ACTIVE CHECK (IS_ACTIVE IN (0,1));

CREATE INDEX IX_USERS_ROLE ON USERS (ROLE_NAME);

-- =========================================================
-- 2) BẢNG NHẬT KÝ HỆ THỐNG
-- =========================================================
CREATE TABLE AUDIT_TRAIL (
    ID            VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    WHO           VARCHAR2(100) NOT NULL,
    ACTION        VARCHAR2(200) NOT NULL,
    EVENT_AT_UTC  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CLIENT_IP     VARCHAR2(45),
    USER_AGENT    VARCHAR2(400)
);

-- =========================================================
-- 3) BẢNG TOKEN KHÔI PHỤC MẬT KHẨU
-- =========================================================
CREATE TABLE PASSWORD_RESET_TOKENS (
    ID               VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    EMAIL            VARCHAR2(255) NOT NULL,
    TOKEN            VARCHAR2(256) NOT NULL,
    EXPIRES_AT_UTC   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT_UTC   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    IS_USED          NUMBER(1,0) DEFAULT 0 NOT NULL
);

ALTER TABLE PASSWORD_RESET_TOKENS ADD CONSTRAINT UQ_PRT_TOKEN UNIQUE (TOKEN);
ALTER TABLE PASSWORD_RESET_TOKENS ADD CONSTRAINT FK_PRT_EMAIL FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL);
CREATE INDEX IX_PRT_EMAIL ON PASSWORD_RESET_TOKENS(EMAIL);

-- =========================================================
-- 4) DEPARTMENTS (Khoa/Phòng)
-- =========================================================
CREATE TABLE DEPARTMENTS (
    ID    VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    CODE  VARCHAR2(50),
    NAME  VARCHAR2(150) NOT NULL
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT UQ_DEPARTMENTS_NAME UNIQUE (NAME);
ALTER TABLE DEPARTMENTS ADD CONSTRAINT UQ_DEPARTMENTS_CODE UNIQUE (CODE);
CREATE INDEX IX_DEPT_NAME ON DEPARTMENTS (NAME);
CREATE INDEX IX_DEPT_CODE ON DEPARTMENTS (CODE);

-- =========================================================
-- 5) CLASSES (Lớp)
-- =========================================================
CREATE TABLE CLASSES (
    ID             VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    CODE           VARCHAR2(50),
    NAME           VARCHAR2(100) NOT NULL,
    DEPARTMENT_ID  VARCHAR2(32)  NULL
);

ALTER TABLE CLASSES ADD CONSTRAINT UQ_CLASSES_NAME UNIQUE (NAME);
ALTER TABLE CLASSES ADD CONSTRAINT UQ_CLASSES_CODE UNIQUE (CODE);
ALTER TABLE CLASSES ADD CONSTRAINT FK_CLASSES_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);
CREATE INDEX IX_CLASSES_DEPT ON CLASSES (DEPARTMENT_ID);
CREATE INDEX IX_CLASSES_CODE ON CLASSES (CODE);

-- =========================================================
-- 6) STUDENTS (Hồ sơ sinh viên)
-- =========================================================
CREATE TABLE STUDENTS (
    USER_ID        VARCHAR2(50)  PRIMARY KEY,
    STUDENT_CODE   VARCHAR2(50),
    CLASS_ID       VARCHAR2(32),
    DEPARTMENT_ID  VARCHAR2(32),
    DATE_OF_BIRTH  DATE,
    GENDER         VARCHAR2(10),
    PHONE          VARCHAR2(30),
    ADDRESS        VARCHAR2(255)
);

ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID);
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);
ALTER TABLE STUDENTS ADD CONSTRAINT UQ_STUDENTS_CODE UNIQUE (STUDENT_CODE);
ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_GENDER CHECK (GENDER IN ('Nam','Nữ','Khác'));
CREATE INDEX IX_STUDENTS_CLASS ON STUDENTS (CLASS_ID);
CREATE INDEX IX_STUDENTS_DEPT  ON STUDENTS (DEPARTMENT_ID);

-- =========================================================
-- 7) TERMS (Học kỳ / năm học)
-- =========================================================
CREATE TABLE TERMS (
    ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    NAME         VARCHAR2(100) NOT NULL,
    YEAR         NUMBER(4),
    TERM_NUMBER  NUMBER(1),
    YEAR_ID      VARCHAR2(20),
    START_DATE   DATE NOT NULL,
    END_DATE     DATE NOT NULL
);

CREATE INDEX IX_TERMS_START ON TERMS (START_DATE);
CREATE INDEX IX_TERMS_YEAR ON TERMS (YEAR, TERM_NUMBER);

-- =========================================================
-- 8) CRITERIA (Tiêu chí DRL)
-- =========================================================
CREATE TABLE CRITERIA (
    ID         VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    GROUP_NO   NUMBER(3)    NOT NULL,
    NAME       VARCHAR2(255) NOT NULL,
    MAX_POINT  NUMBER(5)    NOT NULL
);

CREATE INDEX IX_CRITERIA_GROUP ON CRITERIA (GROUP_NO);

-- =========================================================
-- 9) ACTIVITIES (Hoạt động rèn luyện)
-- =========================================================
CREATE TABLE ACTIVITIES (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TITLE           VARCHAR2(255) NOT NULL,
    DESCRIPTION     CLOB,
    REQUIREMENTS    CLOB,
    BENEFITS        CLOB,
    TERM_ID         VARCHAR2(32)  NOT NULL,
    CRITERION_ID    VARCHAR2(32),
    START_AT        TIMESTAMP(6)  NOT NULL,
    END_AT          TIMESTAMP(6)  NOT NULL,
    STATUS          VARCHAR2(20)  DEFAULT 'OPEN' NOT NULL,
    MAX_SEATS       NUMBER,
    LOCATION        VARCHAR2(200),
    POINTS          NUMBER(5,2),
    APPROVAL_STATUS VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    APPROVED_BY     VARCHAR2(50),
    APPROVED_AT     TIMESTAMP(6),
    ORGANIZER_ID    VARCHAR2(50),
    CREATED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE ACTIVITIES ADD CONSTRAINT CK_ACT_STATUS CHECK (STATUS IN ('OPEN','CLOSED','CANCELLED'));
ALTER TABLE ACTIVITIES ADD CONSTRAINT CK_ACT_APPROVAL CHECK (APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED'));
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_CRITERIA FOREIGN KEY (CRITERION_ID) REFERENCES CRITERIA(ID);
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_APPROVED_BY FOREIGN KEY (APPROVED_BY) REFERENCES USERS(MAND);
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_ORG FOREIGN KEY (ORGANIZER_ID) REFERENCES USERS(MAND);

CREATE INDEX IX_ACT_TERM      ON ACTIVITIES(TERM_ID);
CREATE INDEX IX_ACT_CRITERION ON ACTIVITIES(CRITERION_ID);
CREATE INDEX IX_ACT_APPROVAL  ON ACTIVITIES(APPROVAL_STATUS);
CREATE INDEX IX_ACT_STATUS    ON ACTIVITIES(STATUS);
CREATE INDEX IX_ACT_ORG       ON ACTIVITIES(ORGANIZER_ID);

-- =========================================================
-- 10) REGISTRATIONS (Đăng ký hoạt động)
-- =========================================================
CREATE TABLE REGISTRATIONS (
    ID             VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    ACTIVITY_ID    VARCHAR2(32) NOT NULL,
    STUDENT_ID     VARCHAR2(50) NOT NULL,
    STATUS         VARCHAR2(20) DEFAULT 'REGISTERED' NOT NULL,
    REGISTERED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CHECKED_IN_AT  TIMESTAMP(6)
);

ALTER TABLE REGISTRATIONS ADD CONSTRAINT CK_REG_STATUS CHECK (STATUS IN ('REGISTERED','CHECKED_IN','CANCELLED'));
ALTER TABLE REGISTRATIONS ADD CONSTRAINT UQ_REG_ACTIVITY_STUDENT UNIQUE (ACTIVITY_ID, STUDENT_ID);
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FK_REG_ACT FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID) ON DELETE CASCADE;
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FK_REG_STU FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;

CREATE INDEX IX_REG_ACT     ON REGISTRATIONS(ACTIVITY_ID);
CREATE INDEX IX_REG_STUDENT ON REGISTRATIONS(STUDENT_ID);

-- =========================================================
-- 11) NOTIFICATIONS
-- =========================================================
CREATE TABLE NOTIFICATIONS (
    ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TITLE        VARCHAR2(255) NOT NULL,
    CONTENT      CLOB,
    CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TARGET_ROLE  VARCHAR2(30),
    TO_USER_ID   VARCHAR2(50)
);

ALTER TABLE NOTIFICATIONS ADD CONSTRAINT FK_NOTI_USER FOREIGN KEY (TO_USER_ID) REFERENCES USERS(MAND);
CREATE INDEX IX_NOTI_TOUSER ON NOTIFICATIONS(TO_USER_ID);

-- =========================================================
-- 12) NOTIFICATION_READS
-- =========================================================
CREATE TABLE NOTIFICATION_READS (
  ID               VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
  NOTIFICATION_ID  VARCHAR2(32) NOT NULL,
  STUDENT_ID       VARCHAR2(50) NOT NULL,
  IS_READ          NUMBER(1,0) DEFAULT 0 NOT NULL,
  READ_AT          TIMESTAMP(6)
);

ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT FK_NREADS_NOTI FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATIONS(ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT FK_NREADS_STU FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT UQ_NREADS UNIQUE (NOTIFICATION_ID, STUDENT_ID);
CREATE INDEX IX_NREADS_STU ON NOTIFICATION_READS (STUDENT_ID, IS_READ);

-- =========================================================
-- 13) SCORES (Điểm rèn luyện)
-- =========================================================
CREATE TABLE SCORES (
  ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STUDENT_ID      VARCHAR2(50)   NOT NULL,
  TERM_ID         VARCHAR2(32)   NOT NULL,
  TOTAL_SCORE     NUMBER(5,2)    DEFAULT 70 NOT NULL,
  CLASSIFICATION  VARCHAR2(50),
  STATUS          VARCHAR2(20)   DEFAULT 'PROVISIONAL' NOT NULL,
  APPROVED_BY     VARCHAR2(50),
  APPROVED_AT     TIMESTAMP(6),
  CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE SCORES ADD CONSTRAINT CK_SCORES_STATUS CHECK (STATUS IN ('PROVISIONAL', 'APPROVED'));
ALTER TABLE SCORES ADD CONSTRAINT FK_SCORES_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE SCORES ADD CONSTRAINT FK_SCORES_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE SCORES ADD CONSTRAINT UQ_SCORES_STUDENT_TERM UNIQUE (STUDENT_ID, TERM_ID);
CREATE INDEX IX_SCORES_STATUS ON SCORES (STATUS);
CREATE INDEX IX_SCORES_TERM ON SCORES (TERM_ID);
CREATE INDEX IX_SCORES_CLASSIFICATION ON SCORES (CLASSIFICATION);

-- =========================================================
-- 14) PROOFS
-- =========================================================
CREATE TABLE PROOFS (
    ID               VARCHAR2(32)  DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    REGISTRATION_ID  VARCHAR2(32)  NOT NULL,
    STUDENT_ID       VARCHAR2(50)  NOT NULL,
    ACTIVITY_ID      VARCHAR2(32)  NOT NULL,
    FILE_NAME        VARCHAR2(255) NOT NULL,
    STORED_PATH      VARCHAR2(500) NOT NULL,
    CONTENT_TYPE     VARCHAR2(100) NOT NULL,
    FILE_SIZE        NUMBER        NOT NULL,
    SHA256_HEX       VARCHAR2(64),
    NOTE             VARCHAR2(300),
    STATUS           VARCHAR2(20)  DEFAULT 'SUBMITTED' NOT NULL,
    CREATED_AT_UTC   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    REVIEWED_AT_UTC  TIMESTAMP(6) WITH TIME ZONE
);

ALTER TABLE PROOFS ADD CONSTRAINT CK_PROOFS_STATUS CHECK (STATUS IN ('SUBMITTED','APPROVED','REJECTED'));
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_REG FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATIONS(ID) ON DELETE CASCADE;
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_USER FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_ACT FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID) ON DELETE CASCADE;
CREATE INDEX IX_PROOFS_STU_ACT ON PROOFS (STUDENT_ID, ACTIVITY_ID);
CREATE INDEX IX_PROOFS_REG     ON PROOFS (REGISTRATION_ID);
CREATE INDEX IX_PROOFS_STATUS  ON PROOFS (STATUS);
CREATE INDEX IX_PROOFS_SHA256  ON PROOFS (SHA256_HEX);

-- =========================================================
-- 15) FEEDBACKS
-- =========================================================
CREATE TABLE FEEDBACKS (
    ID            VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    STUDENT_ID    VARCHAR2(50)  NOT NULL,
    TERM_ID       VARCHAR2(32)  NOT NULL,
    CRITERION_ID  VARCHAR2(32),
    TITLE         VARCHAR2(255) NOT NULL,
    CONTENT       CLOB NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'SUBMITTED' NOT NULL,
    RESPONSE      CLOB,
    CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP(6),
    RESPONDED_AT  TIMESTAMP(6)
);

ALTER TABLE FEEDBACKS ADD CONSTRAINT CK_FEEDBACKS_STATUS CHECK (STATUS IN ('DRAFT','SUBMITTED','RESPONDED','CLOSED'));
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_CRITERION FOREIGN KEY (CRITERION_ID) REFERENCES CRITERIA(ID);
CREATE INDEX IX_FEEDBACKS_STU_TERM ON FEEDBACKS (STUDENT_ID, TERM_ID);
CREATE INDEX IX_FEEDBACKS_STATUS   ON FEEDBACKS (STATUS);
CREATE INDEX IX_FEEDBACKS_TERM     ON FEEDBACKS (TERM_ID);

-- =========================================================
-- 16) FEEDBACK_ATTACHMENTS (File đính kèm cho phản hồi điểm)
-- =========================================================
CREATE TABLE FEEDBACK_ATTACHMENTS (
    ID               VARCHAR2(32)  DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    FEEDBACK_ID      VARCHAR2(32)  NOT NULL,   -- FK -> FEEDBACKS(ID)
    FILE_NAME        VARCHAR2(255) NOT NULL,   -- Tên file gốc
    STORED_PATH      VARCHAR2(500) NOT NULL,   -- Đường dẫn lưu trữ
    CONTENT_TYPE     VARCHAR2(100) NOT NULL,   -- MIME type
    FILE_SIZE        NUMBER        NOT NULL,   -- Kích thước (bytes)
    UPLOADED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE FEEDBACK_ATTACHMENTS ADD CONSTRAINT FK_FBATT_FEEDBACK FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACKS(ID) ON DELETE CASCADE;
CREATE INDEX IX_FBATT_FEEDBACK ON FEEDBACK_ATTACHMENTS(FEEDBACK_ID);
CREATE INDEX IX_FBATT_UPLOADED ON FEEDBACK_ATTACHMENTS(UPLOADED_AT);

-- =========================================================
-- 17) CLASS_LECTURERS
-- =========================================================
CREATE TABLE CLASS_LECTURERS (
  ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
  CLASS_ID     VARCHAR2(32) NOT NULL,
  LECTURER_ID  VARCHAR2(50) NOT NULL
);

ALTER TABLE CLASS_LECTURERS ADD CONSTRAINT FK_CM_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID) ON DELETE CASCADE;
ALTER TABLE CLASS_LECTURERS ADD CONSTRAINT FK_CM_LECTURER FOREIGN KEY (LECTURER_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE CLASS_LECTURERS ADD CONSTRAINT UQ_CLASS_MANAGER UNIQUE (CLASS_ID, LECTURER_ID);
CREATE INDEX IX_CM_LECTURER ON CLASS_LECTURERS (LECTURER_ID);
