-- QUẢN LÝ ĐIỂM RÈN LUYỆN - DATABASE SCHEMA

-- =========================================================
-- 1) BẢNG ENCRYPTION_KEYS - RSA Key Management
-- =========================================================
CREATE TABLE ENCRYPTION_KEYS (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    KEY_NAME        VARCHAR2(100) NOT NULL UNIQUE,
    PUBLIC_KEY      CLOB NOT NULL,           -- RSA Public Key (XML format)
    PRIVATE_KEY     CLOB,                    -- RSA Private Key (XML format) - MÃ HÓA
    KEY_SIZE        NUMBER DEFAULT 2048,      -- Key size in bits
    ALGORITHM       VARCHAR2(20) DEFAULT 'RSA',
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50),            -- Username who created the key (nullable)
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    EXPIRES_AT      TIMESTAMP,
    LAST_USED_AT    TIMESTAMP,
    DESCRIPTION     VARCHAR2(500),
    CONSTRAINT CK_ENCKEY_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE INDEX IX_ENCKEY_NAME ON ENCRYPTION_KEYS(KEY_NAME);
CREATE INDEX IX_ENCKEY_ACTIVE ON ENCRYPTION_KEYS(IS_ACTIVE);
CREATE INDEX IX_ENCKEY_CREATED ON ENCRYPTION_KEYS(CREATED_AT);

COMMENT ON TABLE ENCRYPTION_KEYS IS 'Lưu trữ các cặp khóa RSA của hệ thống';
COMMENT ON COLUMN ENCRYPTION_KEYS.PUBLIC_KEY IS 'Public key ở định dạng XML - dùng để mã hóa';
COMMENT ON COLUMN ENCRYPTION_KEYS.PRIVATE_KEY IS 'Private key ở định dạng XML - dùng để giải mã (PHẢI MÃ HÓA)';
COMMENT ON COLUMN ENCRYPTION_KEYS.KEY_NAME IS 'Tên định danh của key (ví dụ: SYSTEM_MAIN_KEY)';

-- =========================================================
-- 2) BẢNG NGƯỜI DÙNG
-- =========================================================
CREATE TABLE USERS(
    MAND VARCHAR2(50),
    EMAIL VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(255) NOT NULL,
    AVATAR_URL VARCHAR2(1000) NULL,
    ROLE_NAME VARCHAR2(50) DEFAULT 'STUDENT' NOT NULL,
    PASSWORD_HASH VARCHAR2(512) NOT NULL,
    PASSWORD_SALT VARCHAR2(256) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    FAILED_LOGIN_COUNT NUMBER(10) DEFAULT 0,
    LOCKOUT_END_UTC TIMESTAMP(6) NULL
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (MAND);
ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL);
ALTER TABLE USERS ADD CONSTRAINT CK_USERS_IS_ACTIVE CHECK (IS_ACTIVE IN (0,1));

CREATE INDEX IX_USERS_ROLE ON USERS (ROLE_NAME);

-- =========================================================
-- 3) BẢNG NHẬT KÝ HỆ THỐNG
-- =========================================================
CREATE TABLE AUDIT_TRAIL (
    ID            VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    WHO           VARCHAR2(100) NOT NULL,
    ACTION        VARCHAR2(200) NOT NULL,
    EVENT_AT_UTC  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CLIENT_IP     VARCHAR2(45),
    USER_AGENT    VARCHAR2(400)
);

-- =========================================================
-- 4) BẢNG TOKEN KHÔI PHỤC MẬT KHẨU
-- =========================================================
CREATE TABLE PASSWORD_RESET_TOKENS (
    ID               VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    EMAIL            VARCHAR2(255) NOT NULL,
    TOKEN            VARCHAR2(256) NOT NULL,
    EXPIRES_AT_UTC   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT_UTC   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    IS_USED          NUMBER(1,0) DEFAULT 0 NOT NULL
);

ALTER TABLE PASSWORD_RESET_TOKENS ADD CONSTRAINT UQ_PRT_TOKEN UNIQUE (TOKEN);
ALTER TABLE PASSWORD_RESET_TOKENS ADD CONSTRAINT FK_PRT_EMAIL FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL);
CREATE INDEX IX_PRT_EMAIL ON PASSWORD_RESET_TOKENS(EMAIL);

-- =========================================================
-- 5) DEPARTMENTS (Khoa/Phòng)
-- =========================================================
CREATE TABLE DEPARTMENTS (
    ID    VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    CODE  VARCHAR2(50),
    NAME  VARCHAR2(150) NOT NULL
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT UQ_DEPARTMENTS_NAME UNIQUE (NAME);
ALTER TABLE DEPARTMENTS ADD CONSTRAINT UQ_DEPARTMENTS_CODE UNIQUE (CODE);
CREATE INDEX IX_DEPT_NAME ON DEPARTMENTS (NAME);
CREATE INDEX IX_DEPT_CODE ON DEPARTMENTS (CODE);

-- =========================================================
-- 6) CLASSES (Lớp)
-- =========================================================
CREATE TABLE CLASSES (
    ID             VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    CODE           VARCHAR2(50),
    NAME           VARCHAR2(100) NOT NULL,
    DEPARTMENT_ID  VARCHAR2(32)  NULL
);

ALTER TABLE CLASSES ADD CONSTRAINT UQ_CLASSES_NAME UNIQUE (NAME);
ALTER TABLE CLASSES ADD CONSTRAINT UQ_CLASSES_CODE UNIQUE (CODE);
ALTER TABLE CLASSES ADD CONSTRAINT FK_CLASSES_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);
CREATE INDEX IX_CLASSES_DEPT ON CLASSES (DEPARTMENT_ID);
CREATE INDEX IX_CLASSES_CODE ON CLASSES (CODE);

-- =========================================================
-- 7) STUDENTS (Hồ sơ sinh viên) - WITH ENCRYPTION SUPPORT
-- =========================================================
CREATE TABLE STUDENTS (
    USER_ID        VARCHAR2(50)  PRIMARY KEY,
    STUDENT_CODE   VARCHAR2(50),
    CLASS_ID       VARCHAR2(32),
    DEPARTMENT_ID  VARCHAR2(32),
    DATE_OF_BIRTH  DATE,
    GENDER         VARCHAR2(10),
    PHONE          VARCHAR2(30),
    ADDRESS        VARCHAR2(255),
    -- Encrypted columns (Migration 001)
    PHONE_ENCRYPTED       CLOB,              -- Số điện thoại mã hóa RSA  
    ADDRESS_ENCRYPTED     CLOB,              -- Địa chỉ mã hóa RSA
    ID_CARD_NUMBER        VARCHAR2(20),      -- Số CMND/CCCD (plaintext - sẽ migrate)
    ID_CARD_ENCRYPTED     CLOB,              -- Số CMND/CCCD mã hóa RSA
    ENCRYPTED_AT          TIMESTAMP,         -- Thời điểm mã hóa
    ENCRYPTION_KEY_ID     VARCHAR2(32)       -- FK to ENCRYPTION_KEYS
);

ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID);
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_ENCKEY FOREIGN KEY (ENCRYPTION_KEY_ID) REFERENCES ENCRYPTION_KEYS(ID);
ALTER TABLE STUDENTS ADD CONSTRAINT UQ_STUDENTS_CODE UNIQUE (STUDENT_CODE);
ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_GENDER CHECK (GENDER IN ('Nam','Nữ','Khác'));

CREATE INDEX IX_STUDENTS_CLASS ON STUDENTS (CLASS_ID);
CREATE INDEX IX_STUDENTS_DEPT  ON STUDENTS (DEPARTMENT_ID);
CREATE INDEX IX_STUDENTS_ENCKEY ON STUDENTS(ENCRYPTION_KEY_ID);
CREATE INDEX IX_STUDENTS_ENCRYPTED ON STUDENTS(ENCRYPTED_AT);

COMMENT ON COLUMN STUDENTS.PHONE_ENCRYPTED IS 'Số điện thoại đã mã hóa RSA';
COMMENT ON COLUMN STUDENTS.ADDRESS_ENCRYPTED IS 'Địa chỉ đã mã hóa RSA';
COMMENT ON COLUMN STUDENTS.ID_CARD_ENCRYPTED IS 'Số CMND/CCCD đã mã hóa RSA';
COMMENT ON COLUMN STUDENTS.ENCRYPTED_AT IS 'Thời điểm data được mã hóa';

-- =========================================================
-- 8) TERMS (Học kỳ / năm học)
-- =========================================================
CREATE TABLE TERMS (
    ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    NAME         VARCHAR2(100) NOT NULL,
    YEAR         NUMBER(4),
    TERM_NUMBER  NUMBER(1),
    YEAR_ID      VARCHAR2(20),
    START_DATE   DATE NOT NULL,
    END_DATE     DATE NOT NULL
);

CREATE INDEX IX_TERMS_START ON TERMS (START_DATE);
CREATE INDEX IX_TERMS_YEAR ON TERMS (YEAR, TERM_NUMBER);

-- =========================================================
-- 9) ACTIVITIES (Hoạt động rèn luyện)
-- =========================================================
CREATE TABLE ACTIVITIES (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TITLE           VARCHAR2(255) NOT NULL,
    DESCRIPTION     CLOB,
    REQUIREMENTS    CLOB,
    BENEFITS        CLOB,
    TERM_ID         VARCHAR2(32)  NOT NULL,
    START_AT        TIMESTAMP(6)  NOT NULL,
    END_AT          TIMESTAMP(6)  NOT NULL,
    STATUS          VARCHAR2(20)  DEFAULT 'OPEN' NOT NULL,
    MAX_SEATS       NUMBER,
    LOCATION        VARCHAR2(200),
    POINTS          NUMBER(3),
    APPROVAL_STATUS VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    APPROVED_BY     VARCHAR2(50),
    APPROVED_AT     TIMESTAMP(6),
    ORGANIZER_ID    VARCHAR2(50),
    CREATED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE ACTIVITIES ADD CONSTRAINT CK_ACT_STATUS CHECK (STATUS IN ('OPEN','CLOSED','CANCELLED'));
ALTER TABLE ACTIVITIES ADD CONSTRAINT CK_ACT_APPROVAL CHECK (APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED'));
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_APPROVED_BY FOREIGN KEY (APPROVED_BY) REFERENCES USERS(MAND);
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_ORG FOREIGN KEY (ORGANIZER_ID) REFERENCES USERS(MAND);

CREATE INDEX IX_ACT_TERM      ON ACTIVITIES(TERM_ID);
CREATE INDEX IX_ACT_CRITERION ON ACTIVITIES(CRITERION_ID);
CREATE INDEX IX_ACT_APPROVAL  ON ACTIVITIES(APPROVAL_STATUS);
CREATE INDEX IX_ACT_STATUS    ON ACTIVITIES(STATUS);
CREATE INDEX IX_ACT_ORG       ON ACTIVITIES(ORGANIZER_ID);

-- =========================================================
-- 11) REGISTRATIONS (Đăng ký hoạt động)
-- =========================================================
CREATE TABLE REGISTRATIONS (
    ID             VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    ACTIVITY_ID    VARCHAR2(32) NOT NULL,
    STUDENT_ID     VARCHAR2(50) NOT NULL,
    STATUS         VARCHAR2(20) DEFAULT 'REGISTERED' NOT NULL,
    REGISTERED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CHECKED_IN_AT  TIMESTAMP(6)
);

ALTER TABLE REGISTRATIONS ADD CONSTRAINT CK_REG_STATUS CHECK (STATUS IN ('REGISTERED','CHECKED_IN','CANCELLED'));
ALTER TABLE REGISTRATIONS ADD CONSTRAINT UQ_REG_ACTIVITY_STUDENT UNIQUE (ACTIVITY_ID, STUDENT_ID);
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FK_REG_ACT FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID) ON DELETE CASCADE;
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FK_REG_STU FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;

CREATE INDEX IX_REG_ACT     ON REGISTRATIONS(ACTIVITY_ID);
CREATE INDEX IX_REG_STUDENT ON REGISTRATIONS(STUDENT_ID);

-- =========================================================
-- 12) NOTIFICATIONS
-- =========================================================
CREATE TABLE NOTIFICATIONS (
    ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TITLE        VARCHAR2(255) NOT NULL,
    CONTENT      CLOB,
    CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TARGET_ROLE  VARCHAR2(30),
    TO_USER_ID   VARCHAR2(50)
);

ALTER TABLE NOTIFICATIONS ADD CONSTRAINT FK_NOTI_USER FOREIGN KEY (TO_USER_ID) REFERENCES USERS(MAND);
CREATE INDEX IX_NOTI_TOUSER ON NOTIFICATIONS(TO_USER_ID);

-- =========================================================
-- 13) NOTIFICATION_READS
-- =========================================================
CREATE TABLE NOTIFICATION_READS (
  ID               VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
  NOTIFICATION_ID  VARCHAR2(32) NOT NULL,
  STUDENT_ID       VARCHAR2(50) NOT NULL,
  IS_READ          NUMBER(1,0) DEFAULT 0 NOT NULL,
  READ_AT          TIMESTAMP(6)
);

ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT FK_NREADS_NOTI FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATIONS(ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT FK_NREADS_STU FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT UQ_NREADS UNIQUE (NOTIFICATION_ID, STUDENT_ID);
CREATE INDEX IX_NREADS_STU ON NOTIFICATION_READS (STUDENT_ID, IS_READ);

-- =========================================================
-- 14) SCORES (Điểm rèn luyện) - WITH DIGITAL SIGNATURE SUPPORT
-- =========================================================
CREATE TABLE SCORES (
  ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STUDENT_ID      VARCHAR2(50)   NOT NULL,
  TERM_ID         VARCHAR2(32)   NOT NULL,
  TOTAL_SCORE     NUMBER(3)      DEFAULT 70 NOT NULL,
  CLASSIFICATION  VARCHAR2(50),
  STATUS          VARCHAR2(20)   DEFAULT 'PROVISIONAL' NOT NULL,
  APPROVED_BY     VARCHAR2(50),
  APPROVED_AT     TIMESTAMP(6),
  CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  DIGITAL_SIGNATURE     CLOB,              -- Chữ ký điện tử RSA (Base64)
  SIGNATURE_ALGORITHM   VARCHAR2(50) DEFAULT 'RSA-SHA256',  -- Thuật toán ký
  SIGNED_DATA_HASH      VARCHAR2(128),     -- Hash SHA-256 của data đã ký
  SIGNATURE_KEY_ID      VARCHAR2(32),      -- FK to ENCRYPTION_KEYS
  SIGNATURE_VERIFIED    NUMBER(1) DEFAULT 0,  -- 1 = đã verify, 0 = chưa
  LAST_VERIFIED_AT      TIMESTAMP,         -- Lần verify cuối
  SIGNED_BY             VARCHAR2(50),      -- User ID người ký
  SIGNED_AT             TIMESTAMP          -- Thời điểm ký
);

ALTER TABLE SCORES ADD CONSTRAINT CK_SCORES_STATUS CHECK (STATUS IN ('PROVISIONAL', 'APPROVED'));
ALTER TABLE SCORES ADD CONSTRAINT CK_SIGNATURE_VERIFIED CHECK (SIGNATURE_VERIFIED IN (0,1));
ALTER TABLE SCORES ADD CONSTRAINT FK_SCORES_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE SCORES ADD CONSTRAINT FK_SCORES_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE SCORES ADD CONSTRAINT FK_SCORES_SIGKEY FOREIGN KEY (SIGNATURE_KEY_ID) REFERENCES ENCRYPTION_KEYS(ID);
ALTER TABLE SCORES ADD CONSTRAINT UQ_SCORES_STUDENT_TERM UNIQUE (STUDENT_ID, TERM_ID);

CREATE INDEX IX_SCORES_STATUS ON SCORES (STATUS);
CREATE INDEX IX_SCORES_TERM ON SCORES (TERM_ID);
CREATE INDEX IX_SCORES_CLASSIFICATION ON SCORES (CLASSIFICATION);
CREATE INDEX IX_SCORES_SIGKEY ON SCORES(SIGNATURE_KEY_ID);
CREATE INDEX IX_SCORES_SIGNED ON SCORES(SIGNED_AT);
CREATE INDEX IX_SCORES_VERIFIED ON SCORES(SIGNATURE_VERIFIED);

COMMENT ON COLUMN SCORES.DIGITAL_SIGNATURE IS 'Chữ ký điện tử RSA-SHA256 của score data';
COMMENT ON COLUMN SCORES.SIGNED_DATA_HASH IS 'Hash SHA-256 của data gốc (để verify)';
COMMENT ON COLUMN SCORES.SIGNATURE_VERIFIED IS '1 = signature đã verify thành công';

-- =========================================================
-- 15) SCORE_AUDIT_SIGNATURES (Audit trail cho chữ ký điện tử)
-- =========================================================
CREATE TABLE SCORE_AUDIT_SIGNATURES (
    ID                VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    SCORE_ID          NUMBER NOT NULL,
    ACTION_TYPE       VARCHAR2(50) NOT NULL,
    PERFORMED_BY      VARCHAR2(50),
    PERFORMED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SIGNATURE_VALUE   CLOB,
    VERIFICATION_RESULT VARCHAR2(20),
    DATA_HASH_BEFORE  VARCHAR2(128),
    DATA_HASH_AFTER   VARCHAR2(128),
    NOTES             VARCHAR2(500),
    CONSTRAINT FK_SCORE_AUDIT_SCORE FOREIGN KEY (SCORE_ID) REFERENCES SCORES(ID) ON DELETE CASCADE,
    CONSTRAINT CK_ACTION_TYPE CHECK (ACTION_TYPE IN ('SIGN', 'VERIFY', 'TAMPER_DETECTED', 'RE_SIGN'))
);

CREATE INDEX IX_AUDIT_SIG_SCORE ON SCORE_AUDIT_SIGNATURES(SCORE_ID);
CREATE INDEX IX_AUDIT_SIG_ACTION ON SCORE_AUDIT_SIGNATURES(ACTION_TYPE);
CREATE INDEX IX_AUDIT_SIG_TIME ON SCORE_AUDIT_SIGNATURES(PERFORMED_AT);

-- =========================================================
-- 16) PROOFS
-- =========================================================
CREATE TABLE PROOFS (
    ID               VARCHAR2(32)  DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    REGISTRATION_ID  VARCHAR2(32)  NOT NULL,
    STUDENT_ID       VARCHAR2(50)  NOT NULL,
    ACTIVITY_ID      VARCHAR2(32)  NOT NULL,
    FILE_NAME        VARCHAR2(255) NOT NULL,
    STORED_PATH      VARCHAR2(500) NOT NULL,
    CONTENT_TYPE     VARCHAR2(100) NOT NULL,
    FILE_SIZE        NUMBER        NOT NULL,
    SHA256_HEX       VARCHAR2(64),
    NOTE             VARCHAR2(300),
    STATUS           VARCHAR2(20)  DEFAULT 'SUBMITTED' NOT NULL,
    CREATED_AT_UTC   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    REVIEWED_AT_UTC  TIMESTAMP(6) WITH TIME ZONE
);

ALTER TABLE PROOFS ADD CONSTRAINT CK_PROOFS_STATUS CHECK (STATUS IN ('SUBMITTED','APPROVED','REJECTED'));
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_REG FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATIONS(ID) ON DELETE CASCADE;
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_USER FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_ACT FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID) ON DELETE CASCADE;
CREATE INDEX IX_PROOFS_STU_ACT ON PROOFS (STUDENT_ID, ACTIVITY_ID);
CREATE INDEX IX_PROOFS_REG     ON PROOFS (REGISTRATION_ID);
CREATE INDEX IX_PROOFS_STATUS  ON PROOFS (STATUS);
CREATE INDEX IX_PROOFS_SHA256  ON PROOFS (SHA256_HEX);

-- =========================================================
-- 17) FEEDBACKS - WITH ENCRYPTION SUPPORT
-- =========================================================
CREATE TABLE FEEDBACKS (
    ID            VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    STUDENT_ID    VARCHAR2(50)  NOT NULL,
    TERM_ID       VARCHAR2(32)  NOT NULL,
    CRITERION_ID  VARCHAR2(32),
    TITLE         VARCHAR2(255) NOT NULL,
    CONTENT       CLOB NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'SUBMITTED' NOT NULL,
    RESPONSE      CLOB,
    CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP(6),
    RESPONDED_AT  TIMESTAMP(6),
    -- Encrypted columns (Migration 003)
    CONTENT_ENCRYPTED     CLOB,              -- Nội dung mã hóa RSA
    RESPONSE_ENCRYPTED    CLOB,              -- Phản hồi mã hóa RSA
    IS_ENCRYPTED          NUMBER(1) DEFAULT 0,  -- 1 = encrypted, 0 = plaintext
    ENCRYPTION_KEY_ID     VARCHAR2(32),      -- FK to ENCRYPTION_KEYS
    ALLOWED_READERS       CLOB,              -- JSON array user IDs được phép đọc
    ENCRYPTED_AT          TIMESTAMP,         -- Thời điểm mã hóa
    ENCRYPTED_BY          VARCHAR2(50)       -- User ID người mã hóa
);

ALTER TABLE FEEDBACKS ADD CONSTRAINT CK_FEEDBACKS_STATUS CHECK (STATUS IN ('DRAFT','SUBMITTED','RESPONDED','CLOSED'));
ALTER TABLE FEEDBACKS ADD CONSTRAINT CK_FEEDBACK_ENCRYPTED CHECK (IS_ENCRYPTED IN (0,1));
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_CRITERION FOREIGN KEY (CRITERION_ID) REFERENCES CRITERIA(ID);
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACK_ENCKEY FOREIGN KEY (ENCRYPTION_KEY_ID) REFERENCES ENCRYPTION_KEYS(ID);

CREATE INDEX IX_FEEDBACKS_STU_TERM ON FEEDBACKS (STUDENT_ID, TERM_ID);
CREATE INDEX IX_FEEDBACKS_STATUS   ON FEEDBACKS (STATUS);
CREATE INDEX IX_FEEDBACKS_TERM     ON FEEDBACKS (TERM_ID);
CREATE INDEX IX_FEEDBACK_ENCRYPTED ON FEEDBACKS(IS_ENCRYPTED);
CREATE INDEX IX_FEEDBACK_ENCKEY ON FEEDBACKS(ENCRYPTION_KEY_ID);

COMMENT ON COLUMN FEEDBACKS.CONTENT_ENCRYPTED IS 'Nội dung phúc khảo đã mã hóa RSA';
COMMENT ON COLUMN FEEDBACKS.RESPONSE_ENCRYPTED IS 'Phản hồi đã mã hóa RSA';
COMMENT ON COLUMN FEEDBACKS.IS_ENCRYPTED IS '1 = dữ liệu đã mã hóa';
COMMENT ON COLUMN FEEDBACKS.ALLOWED_READERS IS 'JSON array các user ID được phép đọc';

-- =========================================================
-- 18) FEEDBACK_ACCESS_LOG (Log truy cập feedback mã hóa)
-- =========================================================
CREATE TABLE FEEDBACK_ACCESS_LOG (
    ID                VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    FEEDBACK_ID       VARCHAR2(32) NOT NULL,
    ACCESSED_BY       VARCHAR2(50) NOT NULL,
    ACCESS_TIME       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACCESS_TYPE       VARCHAR2(20) NOT NULL,  -- READ, WRITE, DECRYPT, ACCESS_DENIED
    ACCESS_RESULT     VARCHAR2(20),  -- SUCCESS, DENIED
    IP_ADDRESS        VARCHAR2(50),
    USER_AGENT        VARCHAR2(200),
    NOTES             VARCHAR2(500),
    CONSTRAINT FK_ACCESS_LOG_FEEDBACK FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACKS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_ACCESS_TYPE CHECK (ACCESS_TYPE IN ('READ', 'WRITE', 'DECRYPT', 'ACCESS_DENIED'))
);

CREATE INDEX IX_ACCESS_FEEDBACK ON FEEDBACK_ACCESS_LOG(FEEDBACK_ID);
CREATE INDEX IX_ACCESS_USER ON FEEDBACK_ACCESS_LOG(ACCESSED_BY);
CREATE INDEX IX_ACCESS_TIME ON FEEDBACK_ACCESS_LOG(ACCESS_TIME);

-- =========================================================
-- 19) FEEDBACK_ATTACHMENTS (File đính kèm cho phản hồi điểm)
-- =========================================================
CREATE TABLE FEEDBACK_ATTACHMENTS (
    ID               VARCHAR2(32)  DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    FEEDBACK_ID      VARCHAR2(32)  NOT NULL,
    FILE_NAME        VARCHAR2(255) NOT NULL,
    STORED_PATH      VARCHAR2(500) NOT NULL,
    CONTENT_TYPE     VARCHAR2(100) NOT NULL,
    FILE_SIZE        NUMBER        NOT NULL,
    UPLOADED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE FEEDBACK_ATTACHMENTS ADD CONSTRAINT FK_FBATT_FEEDBACK FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACKS(ID) ON DELETE CASCADE;
CREATE INDEX IX_FBATT_FEEDBACK ON FEEDBACK_ATTACHMENTS(FEEDBACK_ID);
CREATE INDEX IX_FBATT_UPLOADED ON FEEDBACK_ATTACHMENTS(UPLOADED_AT);

-- =========================================================
-- 20) CLASS_LECTURERS
-- =========================================================
CREATE TABLE CLASS_LECTURERS (
  ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
  CLASS_ID     VARCHAR2(32) NOT NULL,
  LECTURER_ID  VARCHAR2(50) NOT NULL
);

ALTER TABLE CLASS_LECTURERS ADD CONSTRAINT FK_CM_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID) ON DELETE CASCADE;
ALTER TABLE CLASS_LECTURERS ADD CONSTRAINT FK_CM_LECTURER FOREIGN KEY (LECTURER_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE CLASS_LECTURERS ADD CONSTRAINT UQ_CLASS_MANAGER UNIQUE (CLASS_ID, LECTURER_ID);
CREATE INDEX IX_CM_LECTURER ON CLASS_LECTURERS (LECTURER_ID);
