-- ============================================================
-- DROP ALL TABLES - QUẢN LÝ ĐIỂM RÈN LUYỆN
-- Run as: QLDiemRenLuyen
-- ============================================================
-- Lưu ý: Script này sẽ xóa TẤT CẢ dữ liệu trong database
-- ============================================================

SET SERVEROUTPUT ON;

PROMPT '========================================';
PROMPT 'Dropping all tables...';
PROMPT '========================================';

-- Drop tables theo thứ tự ngược lại (child tables trước, parent tables sau)
-- để tránh lỗi foreign key constraints

BEGIN
    -- 22) CLASS_SCORE_PERMISSIONS
    EXECUTE IMMEDIATE 'DROP TABLE CLASS_SCORE_PERMISSIONS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped CLASS_SCORE_PERMISSIONS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- CLASS_SCORE_PERMISSIONS không tồn tại'); END;
/

BEGIN
    -- 21) AUDIT_CONFIG
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_CONFIG CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped AUDIT_CONFIG');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- AUDIT_CONFIG không tồn tại'); END;
/

BEGIN
    -- 20) AUDIT_CHANGE_LOGS
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_CHANGE_LOGS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped AUDIT_CHANGE_LOGS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- AUDIT_CHANGE_LOGS không tồn tại'); END;
/

BEGIN
    -- 19) CLASS_LECTURER_ASSIGNMENTS
    EXECUTE IMMEDIATE 'DROP TABLE CLASS_LECTURER_ASSIGNMENTS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped CLASS_LECTURER_ASSIGNMENTS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- CLASS_LECTURER_ASSIGNMENTS không tồn tại'); END;
/

BEGIN
    -- 18) FEEDBACK_ATTACHMENTS
    EXECUTE IMMEDIATE 'DROP TABLE FEEDBACK_ATTACHMENTS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped FEEDBACK_ATTACHMENTS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- FEEDBACK_ATTACHMENTS không tồn tại'); END;
/

BEGIN
    -- 17) FEEDBACKS
    EXECUTE IMMEDIATE 'DROP TABLE FEEDBACKS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped FEEDBACKS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- FEEDBACKS không tồn tại'); END;
/

BEGIN
    -- 16) PROOFS
    EXECUTE IMMEDIATE 'DROP TABLE PROOFS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped PROOFS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- PROOFS không tồn tại'); END;
/

BEGIN
    -- 15) SCORE_AUDIT_SIGNATURES
    EXECUTE IMMEDIATE 'DROP TABLE SCORE_AUDIT_SIGNATURES CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped SCORE_AUDIT_SIGNATURES');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- SCORE_AUDIT_SIGNATURES không tồn tại'); END;
/

BEGIN
    -- 14) SCORES
    EXECUTE IMMEDIATE 'DROP TABLE SCORES CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped SCORES');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- SCORES không tồn tại'); END;
/

BEGIN
    -- 13) NOTIFICATION_READS
    EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATION_READS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped NOTIFICATION_READS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- NOTIFICATION_READS không tồn tại'); END;
/

BEGIN
    -- 12) NOTIFICATIONS
    EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATIONS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped NOTIFICATIONS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- NOTIFICATIONS không tồn tại'); END;
/

BEGIN
    -- 11) REGISTRATIONS
    EXECUTE IMMEDIATE 'DROP TABLE REGISTRATIONS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped REGISTRATIONS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- REGISTRATIONS không tồn tại'); END;
/

BEGIN
    -- 10) ACTIVITIES
    EXECUTE IMMEDIATE 'DROP TABLE ACTIVITIES CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped ACTIVITIES');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- ACTIVITIES không tồn tại'); END;
/

BEGIN
    -- 9) TERMS
    EXECUTE IMMEDIATE 'DROP TABLE TERMS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped TERMS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- TERMS không tồn tại'); END;
/

BEGIN
    -- 8) STUDENTS
    EXECUTE IMMEDIATE 'DROP TABLE STUDENTS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped STUDENTS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- STUDENTS không tồn tại'); END;
/

BEGIN
    -- 7) CLASSES
    EXECUTE IMMEDIATE 'DROP TABLE CLASSES CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped CLASSES');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- CLASSES không tồn tại'); END;
/

BEGIN
    -- 6) DEPARTMENTS
    EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped DEPARTMENTS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- DEPARTMENTS không tồn tại'); END;
/

BEGIN
    -- 5) SESSION_TOKENS
    EXECUTE IMMEDIATE 'DROP TABLE SESSION_TOKENS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped SESSION_TOKENS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- SESSION_TOKENS không tồn tại'); END;
/

BEGIN
    -- 4) PASSWORD_RESET_TOKENS
    EXECUTE IMMEDIATE 'DROP TABLE PASSWORD_RESET_TOKENS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped PASSWORD_RESET_TOKENS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- PASSWORD_RESET_TOKENS không tồn tại'); END;
/

BEGIN
    -- 3) AUDIT_EVENTS
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_EVENTS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped AUDIT_EVENTS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- AUDIT_EVENTS không tồn tại'); END;
/

BEGIN
    -- 2) USERS
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped USERS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- USERS không tồn tại'); END;
/

BEGIN
    -- 1) ENCRYPTION_KEYS
    EXECUTE IMMEDIATE 'DROP TABLE ENCRYPTION_KEYS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('✓ Dropped ENCRYPTION_KEYS');
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('- ENCRYPTION_KEYS không tồn tại'); END;
/

PROMPT '';
PROMPT '========================================';
PROMPT '✓ All tables dropped successfully!';
PROMPT '========================================';
PROMPT '';
