-- ============================================================
-- QUẢN LÝ ĐIỂM RÈN LUYỆN - DATABASE SCHEMA (Consolidated)
-- Version: 2.0 - Bao gồm tất cả các cột và bảng mã hóa
-- ============================================================
-- Run as: QLDiemRenLuyen
-- ============================================================

-- =========================================================
-- 1) ENCRYPTION_KEYS (Khóa mã hóa RSA + AES)
-- =========================================================
CREATE TABLE ENCRYPTION_KEYS (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    KEY_NAME        VARCHAR2(100) NOT NULL UNIQUE,
    PUBLIC_KEY      CLOB NOT NULL,
    PRIVATE_KEY     CLOB,
    AES_KEY         RAW(32),                      -- AES-256 key for symmetric encryption
    KEY_SIZE        NUMBER DEFAULT 2048,
    ALGORITHM       VARCHAR2(20) DEFAULT 'RSA',
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50),
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    EXPIRES_AT      TIMESTAMP,
    LAST_USED_AT    TIMESTAMP,
    DESCRIPTION     VARCHAR2(500),
    CONSTRAINT CK_ENCKEY_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE INDEX IX_ENCKEY_ACTIVE ON ENCRYPTION_KEYS(IS_ACTIVE);
CREATE INDEX IX_ENCKEY_CREATED ON ENCRYPTION_KEYS(CREATED_AT);

-- =========================================================
-- 2) USERS (Người dùng)
-- =========================================================
CREATE TABLE USERS(
    MAND VARCHAR2(50),
    EMAIL VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(255) NOT NULL,
    AVATAR_URL VARCHAR2(1000) NULL,
    ROLE_NAME VARCHAR2(50) DEFAULT 'STUDENT' NOT NULL,
    PASSWORD_HASH VARCHAR2(512) NOT NULL,
    PASSWORD_SALT VARCHAR2(256) NOT NULL,
    IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    FAILED_LOGIN_COUNT NUMBER(10) DEFAULT 0,
    LOCKOUT_END_UTC TIMESTAMP(6) NULL
);

ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (MAND);
ALTER TABLE USERS ADD CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL);
ALTER TABLE USERS ADD CONSTRAINT CK_USERS_IS_ACTIVE CHECK (IS_ACTIVE IN (0,1));

CREATE INDEX IX_USERS_ROLE ON USERS (ROLE_NAME);

-- =========================================================
-- 3) AUDIT_EVENTS (Nhật ký thống nhất - thay thế AUDIT_TRAIL)
-- =========================================================
CREATE TABLE AUDIT_EVENTS (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    EVENT_CATEGORY  VARCHAR2(20) DEFAULT 'SYSTEM' NOT NULL,
    EVENT_TYPE      VARCHAR2(50) NOT NULL,
    PERFORMED_BY    VARCHAR2(100) NOT NULL,
    EVENT_AT_UTC    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    CLIENT_IP       VARCHAR2(45),
    USER_AGENT      VARCHAR2(400),
    ENTITY_TYPE     VARCHAR2(50),
    ENTITY_ID       VARCHAR2(100),
    DESCRIPTION     VARCHAR2(500),
    DETAILS         CLOB,
    DETAILS_ENCRYPTED     RAW(2000),
    IS_DETAILS_ENCRYPTED  NUMBER(1) DEFAULT 0,
    STATUS          VARCHAR2(20) DEFAULT 'SUCCESS',
    ERROR_MESSAGE   VARCHAR2(1000),
    CONSTRAINT CK_EVENT_CATEGORY CHECK (EVENT_CATEGORY IN ('SYSTEM', 'BUSINESS', 'SECURITY')),
    CONSTRAINT CK_EVENT_STATUS CHECK (STATUS IN ('SUCCESS', 'FAILED', 'PENDING')),
    CONSTRAINT CK_EVENT_ENCRYPTED CHECK (IS_DETAILS_ENCRYPTED IN (0, 1))
);

CREATE INDEX IX_AUDIT_EVENTS_CATEGORY ON AUDIT_EVENTS(EVENT_CATEGORY);
CREATE INDEX IX_AUDIT_EVENTS_TYPE ON AUDIT_EVENTS(EVENT_TYPE);
CREATE INDEX IX_AUDIT_EVENTS_BY ON AUDIT_EVENTS(PERFORMED_BY);
CREATE INDEX IX_AUDIT_EVENTS_AT ON AUDIT_EVENTS(EVENT_AT_UTC);
CREATE INDEX IX_AUDIT_EVENTS_ENTITY ON AUDIT_EVENTS(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IX_AUDIT_EVENTS_STATUS ON AUDIT_EVENTS(STATUS);
CREATE INDEX IX_AUDIT_EVENTS_USER_TIME ON AUDIT_EVENTS(PERFORMED_BY, EVENT_AT_UTC);

-- =========================================================
-- 4) PASSWORD_RESET_TOKENS (Token khôi phục mật khẩu)
-- =========================================================
CREATE TABLE PASSWORD_RESET_TOKENS (
    ID               VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    EMAIL            VARCHAR2(255) NOT NULL,
    TOKEN            VARCHAR2(256) NOT NULL,
    EXPIRES_AT_UTC   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT_UTC   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    IS_USED          NUMBER(1,0) DEFAULT 0 NOT NULL
);

ALTER TABLE PASSWORD_RESET_TOKENS ADD CONSTRAINT UQ_PRT_TOKEN UNIQUE (TOKEN);
ALTER TABLE PASSWORD_RESET_TOKENS ADD CONSTRAINT FK_PRT_EMAIL FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL);
CREATE INDEX IX_PRT_EMAIL ON PASSWORD_RESET_TOKENS(EMAIL);

-- =========================================================
-- 5) SESSION_TOKENS (Token phiên mã hóa AES)
-- =========================================================
CREATE TABLE SESSION_TOKENS (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    USER_MAND       VARCHAR2(50) NOT NULL,
    TOKEN_HASH      VARCHAR2(128) NOT NULL,
    TOKEN_ENCRYPTED RAW(2000),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT      TIMESTAMP NOT NULL,
    LAST_USED_AT    TIMESTAMP,
    IS_VALID        NUMBER(1) DEFAULT 1 NOT NULL,
    CLIENT_IP       VARCHAR2(45),
    USER_AGENT      VARCHAR2(400),
    CONSTRAINT FK_SESSTOKEN_USER FOREIGN KEY (USER_MAND) REFERENCES USERS(MAND) ON DELETE CASCADE,
    CONSTRAINT CK_SESSTOKEN_VALID CHECK (IS_VALID IN (0,1))
);

CREATE INDEX IX_SESSTOKEN_USER ON SESSION_TOKENS(USER_MAND);
CREATE INDEX IX_SESSTOKEN_EXPIRES ON SESSION_TOKENS(EXPIRES_AT);
CREATE INDEX IX_SESSTOKEN_VALID ON SESSION_TOKENS(IS_VALID);

-- =========================================================
-- 6) DEPARTMENTS (Khoa)
-- =========================================================
CREATE TABLE DEPARTMENTS (
    ID    VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    CODE  VARCHAR2(50),
    NAME  VARCHAR2(150) NOT NULL
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT UQ_DEPARTMENTS_NAME UNIQUE (NAME);
ALTER TABLE DEPARTMENTS ADD CONSTRAINT UQ_DEPARTMENTS_CODE UNIQUE (CODE);
CREATE INDEX IX_DEPT_NAME ON DEPARTMENTS (NAME);

-- =========================================================
-- 7) CLASSES (Lớp)
-- =========================================================
CREATE TABLE CLASSES (
    ID             VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    CODE           VARCHAR2(50),
    NAME           VARCHAR2(100) NOT NULL,
    DEPARTMENT_ID  VARCHAR2(32)  NULL
);

ALTER TABLE CLASSES ADD CONSTRAINT UQ_CLASSES_NAME UNIQUE (NAME);
ALTER TABLE CLASSES ADD CONSTRAINT UQ_CLASSES_CODE UNIQUE (CODE);
ALTER TABLE CLASSES ADD CONSTRAINT FK_CLASSES_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);
CREATE INDEX IX_CLASSES_DEPT ON CLASSES (DEPARTMENT_ID);

-- =========================================================
-- 8) STUDENTS (Hồ sơ sinh viên với mã hóa RSA)
-- =========================================================
CREATE TABLE STUDENTS (
    USER_ID        VARCHAR2(50)  PRIMARY KEY,
    STUDENT_CODE   VARCHAR2(50),
    CLASS_ID       VARCHAR2(32),
    DEPARTMENT_ID  VARCHAR2(32),
    DATE_OF_BIRTH  DATE,
    GENDER         VARCHAR2(10),
    PHONE          VARCHAR2(30),
    ADDRESS        VARCHAR2(255),
    PHONE_ENCRYPTED       CLOB,
    ADDRESS_ENCRYPTED     CLOB,
    ID_CARD_NUMBER        VARCHAR2(20),
    ID_CARD_ENCRYPTED     CLOB,
    ENCRYPTED_AT          TIMESTAMP,
    ENCRYPTION_KEY_ID     VARCHAR2(32)
);

ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID);
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID);
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_ENCKEY FOREIGN KEY (ENCRYPTION_KEY_ID) REFERENCES ENCRYPTION_KEYS(ID);
ALTER TABLE STUDENTS ADD CONSTRAINT UQ_STUDENTS_CODE UNIQUE (STUDENT_CODE);
ALTER TABLE STUDENTS ADD CONSTRAINT CK_STUDENTS_GENDER CHECK (GENDER IN ('Nam','Nữ','Khác'));

CREATE INDEX IX_STUDENTS_CLASS ON STUDENTS (CLASS_ID);
CREATE INDEX IX_STUDENTS_DEPT  ON STUDENTS (DEPARTMENT_ID);
CREATE INDEX IX_STUDENTS_ENCKEY ON STUDENTS(ENCRYPTION_KEY_ID);
CREATE INDEX IX_STUDENTS_ENCRYPTED ON STUDENTS(ENCRYPTED_AT);

-- =========================================================
-- 9) TERMS (Học kỳ / năm học)
-- =========================================================
CREATE TABLE TERMS (
    ID                    VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    NAME                  VARCHAR2(100) NOT NULL,
    YEAR                  NUMBER(4),
    TERM_NUMBER           NUMBER(1),
    YEAR_ID               VARCHAR2(20),
    START_DATE            DATE NOT NULL,
    END_DATE              DATE NOT NULL,
    IS_CURRENT            NUMBER(1) DEFAULT 0,
    SCORE_STATUS          VARCHAR2(20) DEFAULT 'PROVISIONAL',
    DRAFT_PUBLISHED_AT    TIMESTAMP,
    FEEDBACK_DEADLINE     TIMESTAMP,
    OFFICIAL_PUBLISHED_AT TIMESTAMP,
    PUBLISHED_BY          VARCHAR2(50)
);

ALTER TABLE TERMS ADD CONSTRAINT CK_TERMS_SCORE_STATUS CHECK (SCORE_STATUS IN ('PROVISIONAL','DRAFT','OFFICIAL'));
ALTER TABLE TERMS ADD CONSTRAINT FK_TERMS_PUBLISHED_BY FOREIGN KEY (PUBLISHED_BY) REFERENCES USERS(MAND);

CREATE INDEX IX_TERMS_START ON TERMS (START_DATE);
CREATE INDEX IX_TERMS_YEAR ON TERMS (YEAR, TERM_NUMBER);
CREATE INDEX IX_TERMS_SCORE_STATUS ON TERMS(SCORE_STATUS);

-- =========================================================
-- 10) ACTIVITIES (Hoạt động)
-- =========================================================
CREATE TABLE ACTIVITIES (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TITLE           VARCHAR2(255) NOT NULL,
    DESCRIPTION     CLOB,
    REQUIREMENTS    CLOB,
    BENEFITS        CLOB,
    TERM_ID         VARCHAR2(32)  NOT NULL,
    START_AT        TIMESTAMP(6)  NOT NULL,
    END_AT          TIMESTAMP(6)  NOT NULL,
    STATUS          VARCHAR2(20)  DEFAULT 'OPEN' NOT NULL,
    MAX_SEATS       NUMBER,
    LOCATION        VARCHAR2(200),
    POINTS          NUMBER(3),
    APPROVAL_STATUS VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    APPROVED_BY     VARCHAR2(50),
    APPROVED_AT     TIMESTAMP(6),
    ORGANIZER_ID    VARCHAR2(50),
    CREATED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    ABSENCE_PENALTY          NUMBER(3) DEFAULT 5,
    ATTENDANCE_STATUS        VARCHAR2(20) DEFAULT 'PENDING',
    ATTENDANCE_CONFIRMED_BY  VARCHAR2(50),
    ATTENDANCE_CONFIRMED_AT  TIMESTAMP(6)
);

ALTER TABLE ACTIVITIES ADD CONSTRAINT CK_ACT_STATUS CHECK (STATUS IN ('OPEN','CLOSED','CANCELLED'));
ALTER TABLE ACTIVITIES ADD CONSTRAINT CK_ACT_APPROVAL CHECK (APPROVAL_STATUS IN ('PENDING','APPROVED','REJECTED'));
ALTER TABLE ACTIVITIES ADD CONSTRAINT CK_ACT_ATT_STATUS CHECK (ATTENDANCE_STATUS IN ('PENDING','IN_PROGRESS','COMPLETED','CONFIRMED'));
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_APPROVED_BY FOREIGN KEY (APPROVED_BY) REFERENCES USERS(MAND);
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_ORG FOREIGN KEY (ORGANIZER_ID) REFERENCES USERS(MAND);
ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACT_ATT_CONFIRMED_BY FOREIGN KEY (ATTENDANCE_CONFIRMED_BY) REFERENCES USERS(MAND);

CREATE INDEX IX_ACT_TERM       ON ACTIVITIES(TERM_ID);
CREATE INDEX IX_ACT_APPROVAL   ON ACTIVITIES(APPROVAL_STATUS);
CREATE INDEX IX_ACT_STATUS     ON ACTIVITIES(STATUS);
CREATE INDEX IX_ACT_ORG        ON ACTIVITIES(ORGANIZER_ID);
CREATE INDEX IX_ACT_ATT_STATUS ON ACTIVITIES(ATTENDANCE_STATUS);

-- =========================================================
-- 11) REGISTRATIONS (Đăng ký hoạt động)
-- =========================================================
CREATE TABLE REGISTRATIONS (
    ID             VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    ACTIVITY_ID    VARCHAR2(32) NOT NULL,
    STUDENT_ID     VARCHAR2(50) NOT NULL,
    STATUS         VARCHAR2(20) DEFAULT 'REGISTERED' NOT NULL,
    REGISTERED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CHECKED_IN_AT  TIMESTAMP(6),
    CHECKED_IN_BY  VARCHAR2(50),
    ATTENDANCE_STATUS  VARCHAR2(20) DEFAULT 'PENDING',
    SCORE_APPLIED      NUMBER(1) DEFAULT 0
);

ALTER TABLE REGISTRATIONS ADD CONSTRAINT CK_REG_STATUS CHECK (STATUS IN ('REGISTERED','CHECKED_IN','CANCELLED'));
ALTER TABLE REGISTRATIONS ADD CONSTRAINT CK_REG_ATT_STATUS CHECK (ATTENDANCE_STATUS IN ('PENDING','PRESENT','ABSENT'));
ALTER TABLE REGISTRATIONS ADD CONSTRAINT CK_REG_SCORE_APPLIED CHECK (SCORE_APPLIED IN (0, 1));
ALTER TABLE REGISTRATIONS ADD CONSTRAINT UQ_REG_ACTIVITY_STUDENT UNIQUE (ACTIVITY_ID, STUDENT_ID);
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FK_REG_ACT FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID) ON DELETE CASCADE;
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FK_REG_STU FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE REGISTRATIONS ADD CONSTRAINT FK_REG_CHECKED_BY FOREIGN KEY (CHECKED_IN_BY) REFERENCES USERS(MAND);

CREATE INDEX IX_REG_ACT           ON REGISTRATIONS(ACTIVITY_ID);
CREATE INDEX IX_REG_STUDENT       ON REGISTRATIONS(STUDENT_ID);
CREATE INDEX IX_REG_CHECKED_BY    ON REGISTRATIONS(CHECKED_IN_BY);
CREATE INDEX IX_REG_ATT_STATUS    ON REGISTRATIONS(ATTENDANCE_STATUS);
CREATE INDEX IX_REG_SCORE_APPLIED ON REGISTRATIONS(SCORE_APPLIED);

-- =========================================================
-- 12) NOTIFICATIONS (Thông báo)
-- =========================================================
CREATE TABLE NOTIFICATIONS (
    ID           VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TITLE        VARCHAR2(255) NOT NULL,
    CONTENT      CLOB,
    CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TARGET_ROLE  VARCHAR2(30),
    TO_USER_ID   VARCHAR2(50)
);

ALTER TABLE NOTIFICATIONS ADD CONSTRAINT FK_NOTI_USER FOREIGN KEY (TO_USER_ID) REFERENCES USERS(MAND);
CREATE INDEX IX_NOTI_TOUSER ON NOTIFICATIONS(TO_USER_ID);

-- =========================================================
-- 13) NOTIFICATION_READS (Đã đọc)
-- =========================================================
CREATE TABLE NOTIFICATION_READS (
  ID               VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
  NOTIFICATION_ID  VARCHAR2(32) NOT NULL,
  STUDENT_ID       VARCHAR2(50) NOT NULL,
  IS_READ          NUMBER(1,0) DEFAULT 0 NOT NULL,
  READ_AT          TIMESTAMP(6)
);

ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT FK_NREADS_NOTI FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATIONS(ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT FK_NREADS_STU FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE NOTIFICATION_READS ADD CONSTRAINT UQ_NREADS UNIQUE (NOTIFICATION_ID, STUDENT_ID);
CREATE INDEX IX_NREADS_STU ON NOTIFICATION_READS (STUDENT_ID, IS_READ);

-- =========================================================
-- 14) SCORES (Điểm rèn luyện với chữ ký số)
-- =========================================================
CREATE TABLE SCORES (
  ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  STUDENT_ID      VARCHAR2(50)   NOT NULL,
  TERM_ID         VARCHAR2(32)   NOT NULL,
  TOTAL_SCORE     NUMBER(3)      DEFAULT 70 NOT NULL,
  CLASSIFICATION  VARCHAR2(50),
  STATUS          VARCHAR2(20)   DEFAULT 'PROVISIONAL' NOT NULL,
  APPROVED_BY     VARCHAR2(50),
  APPROVED_AT     TIMESTAMP(6),
  CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  DIGITAL_SIGNATURE     CLOB,
  SIGNATURE_ALGORITHM   VARCHAR2(50) DEFAULT 'RSA-SHA256',
  SIGNED_DATA_HASH      VARCHAR2(128),
  SIGNATURE_KEY_ID      VARCHAR2(32),
  SIGNATURE_VERIFIED    NUMBER(1) DEFAULT 0,
  LAST_VERIFIED_AT      TIMESTAMP,
  SIGNED_BY             VARCHAR2(50),
  SIGNED_AT             TIMESTAMP
);

ALTER TABLE SCORES ADD CONSTRAINT CK_SCORES_STATUS CHECK (STATUS IN ('PROVISIONAL','DRAFT_PUBLISHED','OFFICIAL','APPROVED'));
ALTER TABLE SCORES ADD CONSTRAINT CK_SIGNATURE_VERIFIED CHECK (SIGNATURE_VERIFIED IN (0,1));
ALTER TABLE SCORES ADD CONSTRAINT FK_SCORES_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE SCORES ADD CONSTRAINT FK_SCORES_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE SCORES ADD CONSTRAINT FK_SCORES_SIGKEY FOREIGN KEY (SIGNATURE_KEY_ID) REFERENCES ENCRYPTION_KEYS(ID);
ALTER TABLE SCORES ADD CONSTRAINT UQ_SCORES_STUDENT_TERM UNIQUE (STUDENT_ID, TERM_ID);

CREATE INDEX IX_SCORES_STATUS ON SCORES (STATUS);
CREATE INDEX IX_SCORES_TERM ON SCORES (TERM_ID);
CREATE INDEX IX_SCORES_CLASSIFICATION ON SCORES (CLASSIFICATION);
CREATE INDEX IX_SCORES_SIGKEY ON SCORES(SIGNATURE_KEY_ID);
CREATE INDEX IX_SCORES_SIGNED ON SCORES(SIGNED_AT);
CREATE INDEX IX_SCORES_VERIFIED ON SCORES(SIGNATURE_VERIFIED);

-- =========================================================
-- 15) SCORE_AUDIT_SIGNATURES (Audit trail cho chữ ký điện tử)
-- =========================================================
CREATE TABLE SCORE_AUDIT_SIGNATURES (
    ID                VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    SCORE_ID          NUMBER NOT NULL,
    ACTION_TYPE       VARCHAR2(50) NOT NULL,
    PERFORMED_BY      VARCHAR2(50),
    PERFORMED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SIGNATURE_VALUE   CLOB,
    VERIFICATION_RESULT VARCHAR2(20),
    DATA_HASH_BEFORE  VARCHAR2(128),
    DATA_HASH_AFTER   VARCHAR2(128),
    NOTES             VARCHAR2(500),
    CONSTRAINT FK_SCORE_AUDIT_SCORE FOREIGN KEY (SCORE_ID) REFERENCES SCORES(ID) ON DELETE CASCADE,
    CONSTRAINT CK_ACTION_TYPE CHECK (ACTION_TYPE IN ('SIGN', 'VERIFY', 'TAMPER_DETECTED', 'RE_SIGN'))
);

CREATE INDEX IX_AUDIT_SIG_SCORE ON SCORE_AUDIT_SIGNATURES(SCORE_ID);
CREATE INDEX IX_AUDIT_SIG_ACTION ON SCORE_AUDIT_SIGNATURES(ACTION_TYPE);
CREATE INDEX IX_AUDIT_SIG_TIME ON SCORE_AUDIT_SIGNATURES(PERFORMED_AT);

-- =========================================================
-- 16) PROOFS (Minh chứng với mã hóa đường dẫn AES)
-- =========================================================
CREATE TABLE PROOFS (
    ID               VARCHAR2(32)  DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    REGISTRATION_ID  VARCHAR2(32)  NOT NULL,
    STUDENT_ID       VARCHAR2(50)  NOT NULL,
    ACTIVITY_ID      VARCHAR2(32)  NOT NULL,
    FILE_NAME        VARCHAR2(255) NOT NULL,
    STORED_PATH      VARCHAR2(500) NOT NULL,
    STORED_PATH_ENCRYPTED RAW(2000),           -- AES encrypted path
    IS_PATH_ENCRYPTED     NUMBER(1) DEFAULT 0, -- Flag for encryption status
    CONTENT_TYPE     VARCHAR2(100) NOT NULL,
    FILE_SIZE        NUMBER        NOT NULL,
    SHA256_HEX       VARCHAR2(64),
    NOTE             VARCHAR2(300),
    STATUS           VARCHAR2(20)  DEFAULT 'SUBMITTED' NOT NULL,
    CREATED_AT_UTC   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
    REVIEWED_AT_UTC  TIMESTAMP(6) WITH TIME ZONE
);

ALTER TABLE PROOFS ADD CONSTRAINT CK_PROOFS_STATUS CHECK (STATUS IN ('SUBMITTED','APPROVED','REJECTED'));
ALTER TABLE PROOFS ADD CONSTRAINT CK_PROOFS_PATH_ENC CHECK (IS_PATH_ENCRYPTED IN (0,1));
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_REG FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATIONS(ID) ON DELETE CASCADE;
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_USER FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE PROOFS ADD CONSTRAINT FK_PROOFS_ACT FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID) ON DELETE CASCADE;
CREATE INDEX IX_PROOFS_STU_ACT ON PROOFS (STUDENT_ID, ACTIVITY_ID);
CREATE INDEX IX_PROOFS_REG     ON PROOFS (REGISTRATION_ID);
CREATE INDEX IX_PROOFS_STATUS  ON PROOFS (STATUS);
CREATE INDEX IX_PROOFS_SHA256  ON PROOFS (SHA256_HEX);
CREATE INDEX IX_PROOFS_PATH_ENC ON PROOFS (IS_PATH_ENCRYPTED);

-- =========================================================
-- 17) FEEDBACKS (Phản hồi với mã hóa RSA/Hybrid)
-- =========================================================
CREATE TABLE FEEDBACKS (
    ID            VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    STUDENT_ID    VARCHAR2(50)  NOT NULL,
    TERM_ID       VARCHAR2(32)  NOT NULL,
    ACTIVITY_ID   VARCHAR2(50),
    TITLE         VARCHAR2(255) NOT NULL,
    CONTENT       CLOB NOT NULL,
    STATUS        VARCHAR2(20) DEFAULT 'SUBMITTED' NOT NULL,
    RESPONSE      CLOB,
    CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP(6),
    RESPONDED_AT  TIMESTAMP(6),
    CONTENT_ENCRYPTED     CLOB,
    RESPONSE_ENCRYPTED    CLOB,
    IS_ENCRYPTED          NUMBER(1) DEFAULT 0,
    ENCRYPTION_KEY_ID     VARCHAR2(32),
    ALLOWED_READERS       CLOB,
    ENCRYPTED_AT          TIMESTAMP,
    ENCRYPTED_BY          VARCHAR2(50)
);

ALTER TABLE FEEDBACKS ADD CONSTRAINT CK_FEEDBACKS_STATUS CHECK (STATUS IN ('DRAFT','SUBMITTED','RESPONDED','CLOSED'));
ALTER TABLE FEEDBACKS ADD CONSTRAINT CK_FEEDBACK_ENCRYPTED CHECK (IS_ENCRYPTED IN (0,1));
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES USERS(MAND) ON DELETE CASCADE;
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_TERM FOREIGN KEY (TERM_ID) REFERENCES TERMS(ID) ON DELETE CASCADE;
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_ACTIVITY FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID);
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACK_ENCKEY FOREIGN KEY (ENCRYPTION_KEY_ID) REFERENCES ENCRYPTION_KEYS(ID);

CREATE INDEX IX_FEEDBACKS_STU_TERM  ON FEEDBACKS (STUDENT_ID, TERM_ID);
CREATE INDEX IX_FEEDBACKS_STATUS    ON FEEDBACKS (STATUS);
CREATE INDEX IX_FEEDBACKS_TERM      ON FEEDBACKS (TERM_ID);
CREATE INDEX IX_FEEDBACKS_ACTIVITY  ON FEEDBACKS(ACTIVITY_ID);
CREATE INDEX IX_FEEDBACK_ENCRYPTED  ON FEEDBACKS(IS_ENCRYPTED);
CREATE INDEX IX_FEEDBACK_ENCKEY     ON FEEDBACKS(ENCRYPTION_KEY_ID);

-- =========================================================
-- 18) FEEDBACK_ATTACHMENTS (File đính kèm với mã hóa đường dẫn)
-- =========================================================
CREATE TABLE FEEDBACK_ATTACHMENTS (
    ID               VARCHAR2(32)  DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    FEEDBACK_ID      VARCHAR2(32)  NOT NULL,
    FILE_NAME        VARCHAR2(255) NOT NULL,
    STORED_PATH      VARCHAR2(500) NOT NULL,
    STORED_PATH_ENCRYPTED RAW(2000),           -- AES encrypted path
    IS_PATH_ENCRYPTED     NUMBER(1) DEFAULT 0, -- Flag for encryption status
    CONTENT_TYPE     VARCHAR2(100) NOT NULL,
    FILE_SIZE        NUMBER        NOT NULL,
    UPLOADED_AT      TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE FEEDBACK_ATTACHMENTS ADD CONSTRAINT FK_FBATT_FEEDBACK FOREIGN KEY (FEEDBACK_ID) REFERENCES FEEDBACKS(ID) ON DELETE CASCADE;
ALTER TABLE FEEDBACK_ATTACHMENTS ADD CONSTRAINT CK_FBATT_PATH_ENC CHECK (IS_PATH_ENCRYPTED IN (0,1));
CREATE INDEX IX_FBATT_FEEDBACK ON FEEDBACK_ATTACHMENTS(FEEDBACK_ID);
CREATE INDEX IX_FBATT_UPLOADED ON FEEDBACK_ATTACHMENTS(UPLOADED_AT);
CREATE INDEX IX_FBATT_PATH_ENC ON FEEDBACK_ATTACHMENTS(IS_PATH_ENCRYPTED);

-- =========================================================
-- 19) CLASS_LECTURER_ASSIGNMENTS (Phân công CVHT)
-- =========================================================
CREATE TABLE CLASS_LECTURER_ASSIGNMENTS (
    ID VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    CLASS_ID VARCHAR2(32) NOT NULL,
    LECTURER_ID VARCHAR2(50) NOT NULL,
    ASSIGNED_BY VARCHAR2(50) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    REMOVED_AT TIMESTAMP,
    REMOVED_BY VARCHAR2(50),
    NOTES VARCHAR2(500),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    
    CONSTRAINT FK_CLA_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CLA_LECTURER FOREIGN KEY (LECTURER_ID) REFERENCES USERS(MAND),
    CONSTRAINT FK_CLA_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY) REFERENCES USERS(MAND),
    CONSTRAINT CK_CLA_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE INDEX IX_CLA_CLASS ON CLASS_LECTURER_ASSIGNMENTS(CLASS_ID);
CREATE INDEX IX_CLA_LECTURER ON CLASS_LECTURER_ASSIGNMENTS(LECTURER_ID);
CREATE INDEX IX_CLA_ACTIVE ON CLASS_LECTURER_ASSIGNMENTS(IS_ACTIVE);
CREATE INDEX IX_CLA_ASSIGNED_AT ON CLASS_LECTURER_ASSIGNMENTS(ASSIGNED_AT);
CREATE INDEX IX_CLA_CLASS_ACTIVE ON CLASS_LECTURER_ASSIGNMENTS(CLASS_ID, IS_ACTIVE);

-- =========================================================
-- 20) AUDIT_CHANGE_LOGS (Audit OLD/NEW values)
-- =========================================================
CREATE TABLE AUDIT_CHANGE_LOGS (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TABLE_NAME      VARCHAR2(100) NOT NULL,
    RECORD_ID       VARCHAR2(100) NOT NULL,
    OPERATION       VARCHAR2(10) NOT NULL,
    OLD_VALUES      CLOB,
    NEW_VALUES      CLOB,
    CHANGED_COLUMNS VARCHAR2(1000),
    PERFORMED_BY    VARCHAR2(50),
    PERFORMED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SESSION_USER    VARCHAR2(50),
    OS_USER         VARCHAR2(100),
    CLIENT_IP       VARCHAR2(45),
    CLIENT_HOST     VARCHAR2(100),
    JUSTIFICATION   VARCHAR2(1000),
    APPLICATION     VARCHAR2(100),
    
    CONSTRAINT CK_AUDIT_OPERATION CHECK (OPERATION IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX IX_AUDIT_LOG_TABLE ON AUDIT_CHANGE_LOGS(TABLE_NAME);
CREATE INDEX IX_AUDIT_LOG_RECORD ON AUDIT_CHANGE_LOGS(TABLE_NAME, RECORD_ID);
CREATE INDEX IX_AUDIT_LOG_TIME ON AUDIT_CHANGE_LOGS(PERFORMED_AT);
CREATE INDEX IX_AUDIT_LOG_USER ON AUDIT_CHANGE_LOGS(PERFORMED_BY);
CREATE INDEX IX_AUDIT_LOG_OP ON AUDIT_CHANGE_LOGS(OPERATION);

-- =========================================================
-- 21) AUDIT_CONFIG (Cấu hình audit)
-- =========================================================
CREATE TABLE AUDIT_CONFIG (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TABLE_NAME      VARCHAR2(100) NOT NULL UNIQUE,
    IS_ENABLED      NUMBER(1) DEFAULT 1 NOT NULL,
    AUDIT_INSERT    NUMBER(1) DEFAULT 1 NOT NULL,
    AUDIT_UPDATE    NUMBER(1) DEFAULT 1 NOT NULL,
    AUDIT_DELETE    NUMBER(1) DEFAULT 1 NOT NULL,
    COLUMNS_TO_AUDIT VARCHAR2(1000),
    RETENTION_DAYS  NUMBER DEFAULT 365,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    
    CONSTRAINT CK_AUDIT_CFG_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CK_AUDIT_CFG_INS CHECK (AUDIT_INSERT IN (0, 1)),
    CONSTRAINT CK_AUDIT_CFG_UPD CHECK (AUDIT_UPDATE IN (0, 1)),
    CONSTRAINT CK_AUDIT_CFG_DEL CHECK (AUDIT_DELETE IN (0, 1))
);

-- =========================================================
-- 22) CLASS_SCORE_PERMISSIONS (DAC - Score Sharing)
-- =========================================================
CREATE TABLE CLASS_SCORE_PERMISSIONS (
    ID VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    CLASS_ID VARCHAR2(32) NOT NULL,
    GRANTED_BY VARCHAR2(50) NOT NULL,
    GRANTED_TO VARCHAR2(50) NOT NULL,
    PERMISSION_TYPE VARCHAR2(20) DEFAULT 'VIEW' NOT NULL,
    GRANTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP,
    REVOKED_AT TIMESTAMP,
    REVOKED_BY VARCHAR2(50),
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    NOTES VARCHAR2(500),
    
    CONSTRAINT FK_CSP_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CSP_GRANTED_BY FOREIGN KEY (GRANTED_BY) REFERENCES USERS(MAND),
    CONSTRAINT FK_CSP_GRANTED_TO FOREIGN KEY (GRANTED_TO) REFERENCES USERS(MAND),
    CONSTRAINT CK_CSP_TYPE CHECK (PERMISSION_TYPE IN ('VIEW', 'EDIT', 'APPROVE')),
    CONSTRAINT CK_CSP_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

CREATE INDEX IX_CSP_CLASS ON CLASS_SCORE_PERMISSIONS(CLASS_ID);
CREATE INDEX IX_CSP_GRANTED_TO ON CLASS_SCORE_PERMISSIONS(GRANTED_TO);
CREATE INDEX IX_CSP_ACTIVE ON CLASS_SCORE_PERMISSIONS(IS_ACTIVE);

-- =========================================================
-- END OF SCHEMA
-- =========================================================
COMMIT;

PROMPT '';
PROMPT '✓ Database schema created successfully!';
PROMPT '  - 22 tables';
PROMPT '  - Encryption support (AES, RSA, Hybrid)';
PROMPT '  - Unified audit (AUDIT_EVENTS)';
PROMPT '';
