CREATE USER QLDiemRenLuyen 
    IDENTIFIED BY "123"
    DEFAULT TABLESPACE USERS
    QUOTA 500M ON USERS;

-- Basic privileges
GRANT CONNECT TO QLDiemRenLuyen;
GRANT RESOURCE TO QLDiemRenLuyen;
GRANT CREATE SESSION TO QLDiemRenLuyen;
GRANT CREATE TABLE TO QLDiemRenLuyen;
GRANT CREATE VIEW TO QLDiemRenLuyen;
GRANT CREATE PROCEDURE TO QLDiemRenLuyen;
GRANT CREATE SEQUENCE TO QLDiemRenLuyen;
GRANT CREATE TRIGGER TO QLDiemRenLuyen;
GRANT CREATE SYNONYM TO QLDiemRenLuyen;

-- Required for encryption
GRANT EXECUTE ON DBMS_CRYPTO TO QLDiemRenLuyen;
GRANT EXECUTE ON UTL_RAW TO QLDiemRenLuyen;
GRANT EXECUTE ON DBMS_RANDOM TO QLDiemRenLuyen;
GRANT SELECT ON DBA_FGA_AUDIT_TRAIL TO QLDiemRenLuyen;

SELECT USERNAME, ACCOUNT_STATUS, DEFAULT_TABLESPACE
FROM DBA_USERS
WHERE USERNAME = 'QLDIEMRENLUYEN';