-- ============================================================================
-- PKG_RSA: Wrapper Package cho các hàm RSA của crypto4ora
--
-- API thực tế của crypto4ora:
--   RSA_ENCRYPT(PLAIN_TEXT VARCHAR2, PRIVATE_KEY VARCHAR2) RETURN VARCHAR2
--   RSA_DECRYPT(ENCRYPTED_TEXT VARCHAR2, PUBLIC_KEY VARCHAR2) RETURN VARCHAR2
--   RSA_SIGN(HASH_MESSAGE VARCHAR2, PUBLIC_KEY VARCHAR2) RETURN VARCHAR2
--   RSA_VERIFY(PLAIN_HASH, SIGNNED_HASH, PRIVATE_KEY) RETURN BOOLEAN
--   RSA_GENERATE_KEYS(KEY_SIZE NUMBER) RETURN VARCHAR2
-- ============================================================================

CREATE OR REPLACE PACKAGE PKG_RSA AS
    
    -- Constants
    G_DEFAULT_KEY_SIZE CONSTANT NUMBER := 2048;
    G_DEFAULT_KEY_NAME CONSTANT VARCHAR2(50) := 'RSA_SYSTEM_KEY';
    
    -- Key Management
    FUNCTION GENERATE_AND_STORE_KEY_PAIR(
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME,
        p_key_size IN NUMBER DEFAULT G_DEFAULT_KEY_SIZE
    ) RETURN VARCHAR2;
    
    PROCEDURE INIT_SYSTEM_KEY(
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME
    );
    
    FUNCTION GET_PUBLIC_KEY(p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME) RETURN VARCHAR2;
    FUNCTION GET_PRIVATE_KEY(p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME) RETURN VARCHAR2;
    
    -- RSA Operations
    FUNCTION RSA_ENCRYPT(p_plaintext IN VARCHAR2, p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME) RETURN VARCHAR2;
    FUNCTION RSA_DECRYPT(p_ciphertext IN VARCHAR2, p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME) RETURN VARCHAR2;
    FUNCTION RSA_SIGN(p_data IN VARCHAR2, p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME) RETURN VARCHAR2;
    FUNCTION RSA_VERIFY(p_data IN VARCHAR2, p_signature IN VARCHAR2, p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME) RETURN NUMBER;
    
    -- Convenience functions
    FUNCTION ENCRYPT_WITH_SYSTEM_KEY(p_plaintext IN VARCHAR2) RETURN VARCHAR2;
    FUNCTION DECRYPT_WITH_SYSTEM_KEY(p_ciphertext IN VARCHAR2) RETURN VARCHAR2;
    FUNCTION SIGN_WITH_SYSTEM_KEY(p_data IN VARCHAR2) RETURN VARCHAR2;
    FUNCTION VERIFY_WITH_SYSTEM_KEY(p_data IN VARCHAR2, p_signature IN VARCHAR2) RETURN NUMBER;

END PKG_RSA;
/

CREATE OR REPLACE PACKAGE BODY PKG_RSA AS

    -- =========================================================================
    -- Helper: Parse key pair from crypto4ora output
    -- =========================================================================
    PROCEDURE PARSE_KEY_PAIR(
        p_key_pair IN VARCHAR2,
        p_public_key OUT VARCHAR2,
        p_private_key OUT VARCHAR2
    ) IS
        v_sep_pos NUMBER;
        v_private_marker VARCHAR2(50) := '-----BEGIN RSA PRIVATE KEY-----';
    BEGIN
        v_sep_pos := INSTR(p_key_pair, v_private_marker);
        IF v_sep_pos > 0 THEN
            p_public_key := TRIM(SUBSTR(p_key_pair, 1, v_sep_pos - 1));
            p_private_key := TRIM(SUBSTR(p_key_pair, v_sep_pos));
        ELSE
            -- Fallback
            v_sep_pos := LENGTH(p_key_pair) / 2;
            p_public_key := SUBSTR(p_key_pair, 1, v_sep_pos);
            p_private_key := SUBSTR(p_key_pair, v_sep_pos + 1);
        END IF;
    END PARSE_KEY_PAIR;

    -- =========================================================================
    -- Key Management
    -- =========================================================================
    
    FUNCTION GENERATE_AND_STORE_KEY_PAIR(
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME,
        p_key_size IN NUMBER DEFAULT G_DEFAULT_KEY_SIZE
    ) RETURN VARCHAR2 IS
        v_key_pair VARCHAR2(32767);
        v_public_key VARCHAR2(32767);
        v_private_key VARCHAR2(32767);
    BEGIN
        -- Generate key pair
        v_key_pair := CRYPTO.RSA_GENERATE_KEYS(KEY_SIZE => p_key_size);
        
        -- Parse keys
        PARSE_KEY_PAIR(v_key_pair, v_public_key, v_private_key);
        
        -- Store in database
        INSERT INTO ENCRYPTION_KEYS (
            KEY_NAME, PUBLIC_KEY, PRIVATE_KEY, KEY_SIZE, 
            ALGORITHM, DESCRIPTION, CREATED_BY, CREATED_AT, IS_ACTIVE
        ) VALUES (
            p_key_name, 
            TO_CLOB(v_public_key), 
            TO_CLOB(v_private_key), 
            p_key_size,
            'RSA-CRYPTO4ORA',
            'RSA key pair generated by crypto4ora',
            USER,
            SYSTIMESTAMP,
            1
        );
        
        COMMIT;
        RETURN p_key_name;
    END GENERATE_AND_STORE_KEY_PAIR;

    PROCEDURE INIT_SYSTEM_KEY(
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME
    ) IS
        v_count NUMBER;
        v_result VARCHAR2(100);
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM ENCRYPTION_KEYS
        WHERE KEY_NAME = p_key_name AND IS_ACTIVE = 1;
        
        IF v_count = 0 THEN
            v_result := GENERATE_AND_STORE_KEY_PAIR(p_key_name, G_DEFAULT_KEY_SIZE);
        END IF;
    END INIT_SYSTEM_KEY;

    FUNCTION GET_PUBLIC_KEY(
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME
    ) RETURN VARCHAR2 IS
        v_key CLOB;
    BEGIN
        SELECT PUBLIC_KEY INTO v_key
        FROM ENCRYPTION_KEYS
        WHERE KEY_NAME = p_key_name AND IS_ACTIVE = 1;
        
        RETURN DBMS_LOB.SUBSTR(v_key, 32767, 1);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'Key not found: ' || p_key_name);
    END GET_PUBLIC_KEY;

    FUNCTION GET_PRIVATE_KEY(
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME
    ) RETURN VARCHAR2 IS
        v_key CLOB;
    BEGIN
        SELECT PRIVATE_KEY INTO v_key
        FROM ENCRYPTION_KEYS
        WHERE KEY_NAME = p_key_name AND IS_ACTIVE = 1;
        
        RETURN DBMS_LOB.SUBSTR(v_key, 32767, 1);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'Key not found: ' || p_key_name);
    END GET_PRIVATE_KEY;

    -- =========================================================================
    -- RSA Operations
    -- Note: crypto4ora uses private key for encrypt, public key for decrypt
    -- =========================================================================
    
    FUNCTION RSA_ENCRYPT(
        p_plaintext IN VARCHAR2,
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME
    ) RETURN VARCHAR2 IS
        v_private_key VARCHAR2(32767);
    BEGIN
        IF p_plaintext IS NULL THEN RETURN NULL; END IF;
        -- crypto4ora: RSA_ENCRYPT(PLAIN_TEXT, PRIVATE_KEY)
        v_private_key := GET_PRIVATE_KEY(p_key_name);
        RETURN CRYPTO.RSA_ENCRYPT(p_plaintext, v_private_key);
    END RSA_ENCRYPT;

    FUNCTION RSA_DECRYPT(
        p_ciphertext IN VARCHAR2,
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME
    ) RETURN VARCHAR2 IS
        v_public_key VARCHAR2(32767);
    BEGIN
        IF p_ciphertext IS NULL THEN RETURN NULL; END IF;
        -- crypto4ora: RSA_DECRYPT(ENCRYPTED_TEXT, PUBLIC_KEY)
        v_public_key := GET_PUBLIC_KEY(p_key_name);
        RETURN CRYPTO.RSA_DECRYPT(p_ciphertext, v_public_key);
    END RSA_DECRYPT;

    FUNCTION RSA_SIGN(
        p_data IN VARCHAR2,
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME
    ) RETURN VARCHAR2 IS
        v_public_key VARCHAR2(32767);
    BEGIN
        IF p_data IS NULL THEN RETURN NULL; END IF;
        -- crypto4ora: RSA_SIGN(HASH_MESSAGE, PUBLIC_KEY)
        v_public_key := GET_PUBLIC_KEY(p_key_name);
        RETURN CRYPTO.RSA_SIGN(p_data, v_public_key);
    END RSA_SIGN;

    FUNCTION RSA_VERIFY(
        p_data IN VARCHAR2,
        p_signature IN VARCHAR2,
        p_key_name IN VARCHAR2 DEFAULT G_DEFAULT_KEY_NAME
    ) RETURN NUMBER IS
        v_private_key VARCHAR2(32767);
        v_result BOOLEAN;
    BEGIN
        IF p_data IS NULL OR p_signature IS NULL THEN RETURN 0; END IF;
        -- crypto4ora: RSA_VERIFY(PLAIN_HASH, SIGNNED_HASH, PRIVATE_KEY) RETURN BOOLEAN
        v_private_key := GET_PRIVATE_KEY(p_key_name);
        v_result := CRYPTO.RSA_VERIFY(p_data, p_signature, v_private_key);
        
        -- Convert BOOLEAN to NUMBER
        IF v_result THEN
            RETURN 1;
        ELSE
            RETURN 0;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN RETURN 0;
    END RSA_VERIFY;

    -- =========================================================================
    -- Convenience Functions
    -- =========================================================================
    
    FUNCTION ENCRYPT_WITH_SYSTEM_KEY(p_plaintext IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN RSA_ENCRYPT(p_plaintext, G_DEFAULT_KEY_NAME);
    END ENCRYPT_WITH_SYSTEM_KEY;

    FUNCTION DECRYPT_WITH_SYSTEM_KEY(p_ciphertext IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN RSA_DECRYPT(p_ciphertext, G_DEFAULT_KEY_NAME);
    END DECRYPT_WITH_SYSTEM_KEY;

    FUNCTION SIGN_WITH_SYSTEM_KEY(p_data IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN RSA_SIGN(p_data, G_DEFAULT_KEY_NAME);
    END SIGN_WITH_SYSTEM_KEY;

    FUNCTION VERIFY_WITH_SYSTEM_KEY(p_data IN VARCHAR2, p_signature IN VARCHAR2) RETURN NUMBER IS
    BEGIN
        RETURN RSA_VERIFY(p_data, p_signature, G_DEFAULT_KEY_NAME);
    END VERIFY_WITH_SYSTEM_KEY;

END PKG_RSA;
/

-- Grant permissions
GRANT EXECUTE ON PKG_RSA TO ROLE_ADMIN;
GRANT EXECUTE ON PKG_RSA TO ROLE_LECTURER;

COMMIT;
