-- ============================================================================
-- Script: Tạo lại RSA Key với format đúng cho crypto4ora
-- Chạy với: QLDiemRenLuyen
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

PROMPT '========================================';
PROMPT 'Tạo lại RSA key...';
PROMPT '========================================';

-- Xóa key cũ (nếu có)
DELETE FROM ENCRYPTION_KEYS WHERE KEY_NAME = 'RSA_SYSTEM_KEY';
COMMIT;

PROMPT 'Đã xóa key cũ';

-- Tạo key mới với format crypto4ora
DECLARE
    v_key_pair CLOB;
    v_public_key CLOB;
    v_private_key CLOB;
    v_pub_end_pos NUMBER;
    v_priv_start_pos NUMBER;
    v_priv_end_pos NUMBER;
    
    -- Markers của crypto4ora
    c_pub_start CONSTANT VARCHAR2(50) := '****publicKey start*****';
    c_pub_end CONSTANT VARCHAR2(50) := '****publicKey end****';
    c_priv_start CONSTANT VARCHAR2(50) := '****privateKey start****';
    c_priv_end CONSTANT VARCHAR2(50) := '****privateKey end****';
BEGIN
    -- Generate key pair từ crypto4ora
    v_key_pair := CRYPTO.RSA_GENERATE_KEYS(KEY_SIZE => 2048);
    
    DBMS_OUTPUT.PUT_LINE('Key pair length: ' || LENGTH(v_key_pair));
    
    -- Tìm vị trí các markers
    v_pub_end_pos := INSTR(v_key_pair, c_pub_end);
    v_priv_start_pos := INSTR(v_key_pair, c_priv_start);
    v_priv_end_pos := INSTR(v_key_pair, c_priv_end);
    
    DBMS_OUTPUT.PUT_LINE('Pub end pos: ' || v_pub_end_pos);
    DBMS_OUTPUT.PUT_LINE('Priv start pos: ' || v_priv_start_pos);
    DBMS_OUTPUT.PUT_LINE('Priv end pos: ' || v_priv_end_pos);
    
    -- Extract public key: từ sau c_pub_start đến trước c_pub_end
    v_public_key := TRIM(SUBSTR(v_key_pair, 
                                LENGTH(c_pub_start) + 1, 
                                v_pub_end_pos - LENGTH(c_pub_start) - 1));
    
    -- Extract private key: từ sau c_priv_start đến trước c_priv_end
    v_private_key := TRIM(SUBSTR(v_key_pair, 
                                 v_priv_start_pos + LENGTH(c_priv_start),
                                 v_priv_end_pos - v_priv_start_pos - LENGTH(c_priv_start)));
    
    DBMS_OUTPUT.PUT_LINE('Public key length: ' || LENGTH(v_public_key));
    DBMS_OUTPUT.PUT_LINE('Private key length: ' || LENGTH(v_private_key));
    DBMS_OUTPUT.PUT_LINE('Public key first 50: ' || SUBSTR(v_public_key, 1, 50));
    DBMS_OUTPUT.PUT_LINE('Private key first 50: ' || SUBSTR(v_private_key, 1, 50));
    
    -- Lưu vào database
    INSERT INTO ENCRYPTION_KEYS (
        KEY_NAME, PUBLIC_KEY, PRIVATE_KEY, KEY_SIZE, 
        ALGORITHM, DESCRIPTION, CREATED_BY, CREATED_AT, IS_ACTIVE
    ) VALUES (
        'RSA_SYSTEM_KEY', 
        v_public_key, 
        v_private_key, 
        2048,
        'RSA-CRYPTO4ORA',
        'RSA key pair generated by crypto4ora',
        USER,
        SYSTIMESTAMP,
        1
    );
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('✓ RSA key pair created successfully!');
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
        ROLLBACK;
        RAISE;
END;
/

-- Kiểm tra kết quả
PROMPT '';
PROMPT 'Kiểm tra key đã tạo:';
SELECT KEY_NAME, KEY_SIZE, IS_ACTIVE, 
       LENGTH(PUBLIC_KEY) AS PUB_LEN, 
       LENGTH(PRIVATE_KEY) AS PRIV_LEN
FROM ENCRYPTION_KEYS 
WHERE KEY_NAME = 'RSA_SYSTEM_KEY';

-- Test encrypt/decrypt
PROMPT '';
PROMPT 'Test mã hóa/giải mã:';
DECLARE
    v_test_data VARCHAR2(100) := 'Hello World 123';
    v_encrypted VARCHAR2(4000);
    v_decrypted VARCHAR2(4000);
BEGIN
    DBMS_OUTPUT.PUT_LINE('Original: ' || v_test_data);
    
    v_encrypted := PKG_RSA.ENCRYPT_WITH_SYSTEM_KEY(v_test_data);
    DBMS_OUTPUT.PUT_LINE('Encrypted length: ' || LENGTH(v_encrypted));
    
    v_decrypted := PKG_RSA.DECRYPT_WITH_SYSTEM_KEY(v_encrypted);
    DBMS_OUTPUT.PUT_LINE('Decrypted: ' || v_decrypted);
    
    IF v_test_data = v_decrypted THEN
        DBMS_OUTPUT.PUT_LINE('✓ Encryption/Decryption test PASSED!');
    ELSE
        DBMS_OUTPUT.PUT_LINE('✗ Test FAILED - data mismatch!');
    END IF;
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('✗ Test FAILED: ' || SQLERRM);
END;
/
