-- =========================================================
-- AUDITING - PART 3: AUDIT TABLES (Run as QLDiemRenLuyen)
-- =========================================================
-- Connection: QLDiemRenLuyen
-- Purpose: Create custom audit tables for OLD/NEW values
-- Prerequisite: Run Parts 1 and 2 first!
-- =========================================================

SET SERVEROUTPUT ON;
SET LINESIZE 200;

PROMPT '========================================';
PROMPT 'AUDITING PART 3 - Audit Tables';
PROMPT 'Executing as: QLDiemRenLuyen';
PROMPT '========================================';

-- =========================================================
-- STEP 1: CREATE AUDIT_CHANGE_LOGS TABLE
-- =========================================================

PROMPT '';
PROMPT 'Creating AUDIT_CHANGE_LOGS table...';

-- Drop if exists
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_CHANGE_LOGS CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped existing AUDIT_CHANGE_LOGS');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUDIT_CHANGE_LOGS (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TABLE_NAME      VARCHAR2(100) NOT NULL,
    RECORD_ID       VARCHAR2(100) NOT NULL,
    OPERATION       VARCHAR2(10) NOT NULL,
    OLD_VALUES      CLOB,
    NEW_VALUES      CLOB,
    CHANGED_COLUMNS VARCHAR2(1000),
    PERFORMED_BY    VARCHAR2(50),
    PERFORMED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SESSION_USER    VARCHAR2(50),
    OS_USER         VARCHAR2(100),
    CLIENT_IP       VARCHAR2(45),
    CLIENT_HOST     VARCHAR2(100),
    JUSTIFICATION   VARCHAR2(1000),
    APPLICATION     VARCHAR2(100),
    
    CONSTRAINT CK_AUDIT_OPERATION CHECK (OPERATION IN ('INSERT', 'UPDATE', 'DELETE'))
);

COMMENT ON TABLE AUDIT_CHANGE_LOGS IS 'Custom audit log capturing OLD/NEW values with justification';
COMMENT ON COLUMN AUDIT_CHANGE_LOGS.OLD_VALUES IS 'JSON format of old values before change';
COMMENT ON COLUMN AUDIT_CHANGE_LOGS.NEW_VALUES IS 'JSON format of new values after change';
COMMENT ON COLUMN AUDIT_CHANGE_LOGS.JUSTIFICATION IS 'Reason provided by user for the change';

-- Create indexes
CREATE INDEX IX_AUDIT_LOG_TABLE ON AUDIT_CHANGE_LOGS(TABLE_NAME);
CREATE INDEX IX_AUDIT_LOG_RECORD ON AUDIT_CHANGE_LOGS(TABLE_NAME, RECORD_ID);
CREATE INDEX IX_AUDIT_LOG_TIME ON AUDIT_CHANGE_LOGS(PERFORMED_AT);
CREATE INDEX IX_AUDIT_LOG_USER ON AUDIT_CHANGE_LOGS(PERFORMED_BY);
CREATE INDEX IX_AUDIT_LOG_OP ON AUDIT_CHANGE_LOGS(OPERATION);

PROMPT '✓ Created AUDIT_CHANGE_LOGS table';

-- =========================================================
-- STEP 2: CREATE AUDIT_CONFIG TABLE
-- =========================================================

PROMPT '';
PROMPT 'Creating AUDIT_CONFIG table...';

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_CONFIG CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUDIT_CONFIG (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    TABLE_NAME      VARCHAR2(100) NOT NULL UNIQUE,
    IS_ENABLED      NUMBER(1) DEFAULT 1 NOT NULL,
    AUDIT_INSERT    NUMBER(1) DEFAULT 1 NOT NULL,
    AUDIT_UPDATE    NUMBER(1) DEFAULT 1 NOT NULL,
    AUDIT_DELETE    NUMBER(1) DEFAULT 1 NOT NULL,
    COLUMNS_TO_AUDIT VARCHAR2(1000),
    RETENTION_DAYS  NUMBER DEFAULT 365,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    
    CONSTRAINT CK_AUDIT_CFG_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CK_AUDIT_CFG_INS CHECK (AUDIT_INSERT IN (0, 1)),
    CONSTRAINT CK_AUDIT_CFG_UPD CHECK (AUDIT_UPDATE IN (0, 1)),
    CONSTRAINT CK_AUDIT_CFG_DEL CHECK (AUDIT_DELETE IN (0, 1))
);

COMMENT ON TABLE AUDIT_CONFIG IS 'Configuration for which tables/operations to audit';

PROMPT '✓ Created AUDIT_CONFIG table';

-- =========================================================
-- STEP 3: INSERT DEFAULT AUDIT CONFIGURATION
-- =========================================================

PROMPT '';
PROMPT 'Inserting default audit configuration...';

-- SCORES - High importance, audit all
INSERT INTO AUDIT_CONFIG(TABLE_NAME, IS_ENABLED, AUDIT_INSERT, AUDIT_UPDATE, AUDIT_DELETE, COLUMNS_TO_AUDIT)
VALUES ('SCORES', 1, 1, 1, 1, 'TOTAL_SCORE,CLASSIFICATION,STATUS,APPROVED_BY,APPROVED_AT');

-- USERS - High importance, audit all
INSERT INTO AUDIT_CONFIG(TABLE_NAME, IS_ENABLED, AUDIT_INSERT, AUDIT_UPDATE, AUDIT_DELETE, COLUMNS_TO_AUDIT)
VALUES ('USERS', 1, 1, 1, 1, 'ROLE_NAME,IS_ACTIVE,EMAIL,FULL_NAME');

-- FEEDBACKS - Medium importance
INSERT INTO AUDIT_CONFIG(TABLE_NAME, IS_ENABLED, AUDIT_INSERT, AUDIT_UPDATE, AUDIT_DELETE, COLUMNS_TO_AUDIT)
VALUES ('FEEDBACKS', 1, 1, 1, 0, 'STATUS,RESPONSE,RESPONDED_AT');

-- ACTIVITIES - Update only (approval)
INSERT INTO AUDIT_CONFIG(TABLE_NAME, IS_ENABLED, AUDIT_INSERT, AUDIT_UPDATE, AUDIT_DELETE, COLUMNS_TO_AUDIT)
VALUES ('ACTIVITIES', 1, 0, 1, 0, 'APPROVAL_STATUS,APPROVED_BY,APPROVED_AT,STATUS');

-- PROOFS - Update only (status)
INSERT INTO AUDIT_CONFIG(TABLE_NAME, IS_ENABLED, AUDIT_INSERT, AUDIT_UPDATE, AUDIT_DELETE, COLUMNS_TO_AUDIT)
VALUES ('PROOFS', 1, 0, 1, 0, 'STATUS,REVIEWED_AT_UTC');

-- CLASS_LECTURER_ASSIGNMENTS
INSERT INTO AUDIT_CONFIG(TABLE_NAME, IS_ENABLED, AUDIT_INSERT, AUDIT_UPDATE, AUDIT_DELETE, COLUMNS_TO_AUDIT)
VALUES ('CLASS_LECTURER_ASSIGNMENTS', 1, 1, 1, 0, 'LECTURER_ID,IS_ACTIVE,REMOVED_AT,REMOVED_BY');

COMMIT;

PROMPT '✓ Inserted default audit configuration';

-- =========================================================
-- STEP 4: CREATE AUDIT_BUSINESS_ACTIONS TABLE
-- =========================================================

PROMPT '';
PROMPT 'Creating AUDIT_BUSINESS_ACTIONS table...';

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_BUSINESS_ACTIONS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUDIT_BUSINESS_ACTIONS (
    ID              VARCHAR2(32) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    ACTION_TYPE     VARCHAR2(50) NOT NULL,
    ACTION_DESC     VARCHAR2(500) NOT NULL,
    ENTITY_TYPE     VARCHAR2(50),
    ENTITY_ID       VARCHAR2(100),
    PERFORMED_BY    VARCHAR2(50),
    PERFORMED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CLIENT_IP       VARCHAR2(45),
    DETAILS         CLOB,
    STATUS          VARCHAR2(20),
    ERROR_MESSAGE   VARCHAR2(1000)
);

COMMENT ON TABLE AUDIT_BUSINESS_ACTIONS IS 'Log for business-level actions not captured by triggers';

-- Indexes
CREATE INDEX IX_BIZ_ACTION_TYPE ON AUDIT_BUSINESS_ACTIONS(ACTION_TYPE);
CREATE INDEX IX_BIZ_ACTION_TIME ON AUDIT_BUSINESS_ACTIONS(PERFORMED_AT);
CREATE INDEX IX_BIZ_ACTION_USER ON AUDIT_BUSINESS_ACTIONS(PERFORMED_BY);
CREATE INDEX IX_BIZ_ACTION_ENTITY ON AUDIT_BUSINESS_ACTIONS(ENTITY_TYPE, ENTITY_ID);

PROMPT '✓ Created AUDIT_BUSINESS_ACTIONS table';

-- =========================================================
-- VERIFICATION
-- =========================================================

PROMPT '';
PROMPT '========================================';
PROMPT 'VERIFICATION - Audit Tables';
PROMPT '========================================';

PROMPT '';
PROMPT 'Tables created:';
SELECT TABLE_NAME, NUM_ROWS
FROM USER_TABLES
WHERE TABLE_NAME LIKE 'AUDIT%'
ORDER BY TABLE_NAME;

PROMPT '';
PROMPT 'Audit configuration:';
SELECT TABLE_NAME, IS_ENABLED, AUDIT_INSERT, AUDIT_UPDATE, AUDIT_DELETE
FROM AUDIT_CONFIG
ORDER BY TABLE_NAME;

PROMPT '';
PROMPT '========================================';
PROMPT '✓ PART 3 COMPLETED!';
PROMPT 'Tables created:';
PROMPT '  - AUDIT_CHANGE_LOGS (OLD/NEW values)';
PROMPT '  - AUDIT_CONFIG (configuration)';
PROMPT '  - AUDIT_BUSINESS_ACTIONS (business events)';
PROMPT '';
PROMPT 'Next: Run Part 4 to create triggers';
PROMPT '========================================';
