-- ==================== STEP 1: ALTER SCORES TABLE ====================

-- Add new columns for publication workflow
ALTER TABLE SCORES ADD (
    PUBLISHED_AT TIMESTAMP,
    FEEDBACK_DEADLINE TIMESTAMP,
    IS_LOCKED NUMBER(1) DEFAULT 0
);

-- Add check constraint for IS_LOCKED
ALTER TABLE SCORES ADD CONSTRAINT CK_SCORES_LOCKED 
    CHECK (IS_LOCKED IN (0, 1));

-- Drop old STATUS constraint
ALTER TABLE SCORES DROP CONSTRAINT CK_SCORES_STATUS;

-- Add new STATUS constraint with expanded values
ALTER TABLE SCORES ADD CONSTRAINT CK_SCORES_STATUS 
    CHECK (STATUS IN ('PROVISIONAL', 'APPROVED', 'DRAFT_PUBLISHED', 'FINAL_PUBLISHED'));

COMMIT;

-- ==================== STEP 2: EXTEND FEEDBACKS TABLE ===================

-- Add SCORE_ID column to link feedback to specific score
ALTER TABLE FEEDBACKS ADD (
    SCORE_ID NUMBER,
    REQUESTED_SCORE NUMBER(3)
);

-- Add foreign key
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_SCORE 
    FOREIGN KEY (SCORE_ID) REFERENCES SCORES(ID) ON DELETE CASCADE;

-- Add index for performance
CREATE INDEX IDX_FEEDBACKS_SCORE ON FEEDBACKS(SCORE_ID);

COMMIT;

-- NOTE: FEEDBACKS table now used for score publication feedback

-- ==================== STEP 3: CREATE HELPER VIEWS ====================

-- View to get publication statistics per term
CREATE OR REPLACE VIEW V_SCORE_PUBLICATION_STATS AS
SELECT 
    t.ID as TERM_ID,
    t.NAME as TERM_NAME,
    COUNT(DISTINCT s.STUDENT_ID) as TOTAL_STUDENTS,
    COUNT(DISTINCT CASE WHEN s.STATUS IN ('DRAFT_PUBLISHED', 'FINAL_PUBLISHED') THEN s.STUDENT_ID END) as PUBLISHED_COUNT,
    COUNT(DISTINCT CASE WHEN s.STATUS = 'FINAL_PUBLISHED' THEN s.STUDENT_ID END) as FINAL_COUNT,
    COUNT(DISTINCT f.STUDENT_ID) as STUDENTS_WITH_FEEDBACK,
    MAX(s.PUBLISHED_AT) as LAST_PUBLISHED_AT,
    MAX(s.FEEDBACK_DEADLINE) as FEEDBACK_DEADLINE
FROM TERMS t
LEFT JOIN SCORES s ON t.ID = s.TERM_ID
LEFT JOIN FEEDBACKS f ON s.ID = f.SCORE_ID AND f.STATUS != 'CLOSED'
GROUP BY t.ID, t.NAME;

-- View to get pending score feedbacks for admin
CREATE OR REPLACE VIEW V_PENDING_SCORE_FEEDBACKS AS
SELECT 
    f.ID,
    f.SCORE_ID,
    f.STUDENT_ID,
    u.FULL_NAME as STUDENT_NAME,
    st.STUDENT_CODE,
    f.TERM_ID,
    t.NAME as TERM_NAME,
    s.TOTAL_SCORE as CURRENT_SCORE,
    f.REQUESTED_SCORE as EXPECTED_SCORE,
    f.TITLE,
    f.CONTENT as FEEDBACK_TEXT,
    f.CREATED_AT as SUBMITTED_AT,
    f.STATUS,
    f.RESPONSE as ADMIN_RESPONSE,
    f.RESPONDED_AT,
    CASE 
        WHEN SYSDATE > s.FEEDBACK_DEADLINE THEN 1
        ELSE 0
    END as IS_PAST_DEADLINE
FROM FEEDBACKS f
INNER JOIN SCORES s ON f.SCORE_ID = s.ID
INNER JOIN USERS u ON f.STUDENT_ID = u.MAND
INNER JOIN STUDENTS st ON f.STUDENT_ID = st.MAND
INNER JOIN TERMS t ON f.TERM_ID = t.ID
WHERE f.SCORE_ID IS NOT NULL  -- Only score-related feedbacks
  AND f.STATUS IN ('SUBMITTED', 'RESPONDED')
ORDER BY f.CREATED_AT ASC;

COMMIT;

-- ==================== STEP 4: CREATE AUDIT TRAIL ====================

-- Create audit table for publication actions
CREATE TABLE SCORE_PUBLICATION_HISTORY (
    ID VARCHAR2(50) PRIMARY KEY,
    TERM_ID VARCHAR2(50) NOT NULL,
    ACTION VARCHAR2(50) NOT NULL,
    PERFORMED_BY VARCHAR2(50) NOT NULL,
    PERFORMED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FEEDBACK_DEADLINE TIMESTAMP,
    AFFECTED_STUDENTS NUMBER,
    NOTES VARCHAR2(500),
    
    CONSTRAINT FK_PUB_HISTORY_TERM FOREIGN KEY (TERM_ID) 
        REFERENCES TERMS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PUB_HISTORY_USER FOREIGN KEY (PERFORMED_BY) 
        REFERENCES USERS(MAND),
    CONSTRAINT CK_PUB_ACTION 
        CHECK (ACTION IN ('PUBLISH_DRAFT', 'PUBLISH_FINAL', 'REPUBLISH_DRAFT', 'UNLOCK'))
);

CREATE INDEX IDX_PUB_HISTORY_TERM ON SCORE_PUBLICATION_HISTORY(TERM_ID);
CREATE INDEX IDX_PUB_HISTORY_ACTION ON SCORE_PUBLICATION_HISTORY(ACTION);

COMMIT;

-- ==================== VERIFICATION ====================

-- Verify new columns in SCORES
SELECT column_name, data_type, nullable 
FROM user_tab_columns 
WHERE table_name = 'SCORES' 
  AND column_name IN ('PUBLISHED_AT', 'FEEDBACK_DEADLINE', 'IS_LOCKED')
ORDER BY column_name;

-- Verify new columns in FEEDBACKS
SELECT column_name, data_type, nullable 
FROM user_tab_columns 
WHERE table_name = 'FEEDBACKS' 
  AND column_name IN ('SCORE_ID', 'REQUESTED_SCORE')
ORDER BY column_name;

-- Verify views
SELECT view_name 
FROM user_views 
WHERE view_name IN ('V_SCORE_PUBLICATION_STATS', 'V_PENDING_SCORE_FEEDBACKS');

-- Verify audit table
SELECT table_name 
FROM user_tables 
WHERE table_name = 'SCORE_PUBLICATION_HISTORY';

-- Test queries - should return no errors
SELECT * FROM V_SCORE_PUBLICATION_STATS WHERE 1=0;
SELECT * FROM V_PENDING_SCORE_FEEDBACKS WHERE 1=0;

-- ==================== SUCCESS MESSAGE ====================

BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('MIGRATION COMPLETED SUCCESSFULLY');
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('Changes applied:');
    DBMS_OUTPUT.PUT_LINE('  1. SCORES table: +3 columns');
    DBMS_OUTPUT.PUT_LINE('  2. FEEDBACKS table: +2 columns (reused)');
    DBMS_OUTPUT.PUT_LINE('  3. V_SCORE_PUBLICATION_STATS: created');
    DBMS_OUTPUT.PUT_LINE('  4. V_PENDING_SCORE_FEEDBACKS: created');
    DBMS_OUTPUT.PUT_LINE('  5. SCORE_PUBLICATION_HISTORY: created');
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('FEEDBACKS table: Score publication feedback support added');
    DBMS_OUTPUT.PUT_LINE('  - SCORE_ID column links feedback to specific score');
    DBMS_OUTPUT.PUT_LINE('  - REQUESTED_SCORE stores student expected score');
    DBMS_OUTPUT.PUT_LINE('========================================');
END;
/

-- ==================== ROLLBACK SCRIPT (if needed) ====================
/*
-- To rollback this migration, run:

DROP VIEW V_PENDING_SCORE_FEEDBACKS;
DROP VIEW V_SCORE_PUBLICATION_STATS;
DROP TABLE SCORE_PUBLICATION_HISTORY;

DROP INDEX IDX_FEEDBACKS_SCORE;
ALTER TABLE FEEDBACKS DROP CONSTRAINT FK_FEEDBACKS_SCORE;
ALTER TABLE FEEDBACKS DROP COLUMN SCORE_ID;
ALTER TABLE FEEDBACKS DROP COLUMN REQUESTED_SCORE;

ALTER TABLE SCORES DROP COLUMN PUBLISHED_AT;
ALTER TABLE SCORES DROP COLUMN FEEDBACK_DEADLINE;
ALTER TABLE SCORES DROP COLUMN IS_LOCKED;
ALTER TABLE SCORES DROP CONSTRAINT CK_SCORES_LOCKED;

-- Recreate old STATUS constraint
ALTER TABLE SCORES DROP CONSTRAINT CK_SCORES_STATUS;
ALTER TABLE SCORES ADD CONSTRAINT CK_SCORES_STATUS 
    CHECK (STATUS IN ('PROVISIONAL', 'APPROVED'));

COMMIT;
*/
